define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Definiu la infografia que estarà disponible al widget:",
  "defineWhichReports": "Definiu els informes que estaran disponibles al widget:",
  "defaultValues": "Valors per defecte:",
  "disable": "Deshabilita",
  "driveTime": "Temps de recorregut",
  "infographics": "Infografia",
  "invalidValueRing": "Els valors han d'estar en un interval de 0 a 1.000.",
  "invalidValueDTWT": "Els valors han d'estar en un interval de 0 a 300.",
  "km": "km",
  "makeDefault": "Defineix-lo per defecte",
  "miles": "milles",
  "minutes": "minuts",
  "radius": "Radi",
  "removeDefault": "Elimina el valor per defecte",
  "reports": "Informes",
  "rings": "Anells",
  "selectCountryOrRegion": "Seleccioneu un país o una regió:",
  "thisEntryIsNotValid": "Aquesta entrada no és vàlida.",
  "time": "Temps",
  "walkTime": "Temps de recorregut a peu"
});