// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/supportClasses/PlayerConfigurator","../PlayerResizeModes ../PlayerZoomBehaviors ../PlayerThemes ../PlayerViewModes ../config esri/dijit/geoenrichment/utils/DeviceUtil".split(" "),function(b,c,h,d,g,f){var e={configurePlayer:function(a,k){a._originalConfigurationSettings||(a.theme=a.theme&&h.toSupportedValue(a.theme)||h.DARK,a.viewMode=a.viewMode&&d.toSupportedValue(a.viewMode),a.resizeMode=a.resizeMode&&b.toSupportedValue(a.resizeMode)||b.FIT_WINDOW,a.defaultZoomBehavior=
a.defaultZoomBehavior&&c.toSupportedValue(a.defaultZoomBehavior),a._originalConfigurationSettings={viewMode:a.viewMode,defaultZoomBehavior:a.defaultZoomBehavior,scaleSlidesToFitWindow:a.scaleSlidesToFitWindow,showAreaTitle:a.showAreaTitle});a.viewMode=k||a._originalConfigurationSettings.viewMode||e.getDefaultViewMode(a);switch(a.viewMode){case d.FULL_PAGES:e._configure_fullPages(a);break;case d.PANELS_IN_SLIDES:e._configure_panelsInSlides(a);break;case d.PANELS_IN_STACK:e._configure_panelsInStack(a);
break;case d.PANELS_IN_STACK_ALL:e._configure_panelsInStackAll(a)}a._viewModel.setAnimationSuspended(a.viewMode===d.PANELS_IN_STACK_ALL);f.isMobileDevice()&&(g.modules.exportCommands=!1);g.modules.complexCellTooltips=a.viewMode===d.FULL_PAGES||a.viewMode===d.PANELS_IN_STACK_ALL},getDefaultViewMode:function(a){return f.isMobileDevice()&&!f.isWebLayout()?f.isLandscape()?d.PANELS_IN_SLIDES:d.PANELS_IN_STACK:d.FULL_PAGES},_configure_fullPages:function(a){a.showAreaTitle=!1!==a._originalConfigurationSettings.showAreaTitle;
a.scaleSlidesToFitWindow=!1;switch(a.resizeMode){case b.FIT_WINDOW:a.defaultZoomBehavior=a._originalConfigurationSettings.defaultZoomBehavior||(f.isMobileDevice()?c.FIT_PAGE_WIDTH:null)||c.FIT_PAGE;break;case b.AUTO:a.defaultZoomBehavior=c.RESET;break;case b.MANUAL:a.defaultZoomBehavior=a._originalConfigurationSettings.defaultZoomBehavior||c.FIT_PAGE}},_configure_panelsInSlides:function(a){a.showAreaTitle=!!a._originalConfigurationSettings.showAreaTitle;a.defaultZoomBehavior=null;switch(a.resizeMode){case b.FIT_WINDOW:a.scaleSlidesToFitWindow=
!1!==a._originalConfigurationSettings.scaleSlidesToFitWindow;break;case b.AUTO:a.scaleSlidesToFitWindow=!1;break;case b.MANUAL:a.scaleSlidesToFitWindow=!1!==a._originalConfigurationSettings.scaleSlidesToFitWindow}},_configure_panelsInStack:function(a){a.showAreaTitle=!!a._originalConfigurationSettings.showAreaTitle;a.scaleSlidesToFitWindow=!1;switch(a.resizeMode){case b.FIT_WINDOW:a.defaultZoomBehavior=c.FIT_PAGE_WIDTH;break;case b.AUTO:a.defaultZoomBehavior=c.RESET;break;case b.MANUAL:a.defaultZoomBehavior=
c.FIT_PAGE_WIDTH}},_configure_panelsInStackAll:function(a){a.showAreaTitle=!1!==a._originalConfigurationSettings.showAreaTitle;a.scaleSlidesToFitWindow=!1;switch(a.resizeMode){case b.FIT_WINDOW:a.defaultZoomBehavior=c.FIT_PAGE_WIDTH;break;case b.AUTO:a.defaultZoomBehavior=c.RESET;break;case b.MANUAL:a.defaultZoomBehavior=c.FIT_PAGE_WIDTH}},configurePlayerForCustomBuild:function(a,b){b=b||g;b.esriDijitCssUrl=a+"/dijit/themes/claro/claro.css";b.esriCssUrl=a+"/esri/css/esri.css";b.playerSourceRootUrl=
a+"/dojo/dojo.js";b.configScriptText='var dojoConfig \x3d { baseUrl: "'+a+'/", waitSeconds: 60, async: true, locale: typeof dojoConfig !\x3d\x3d "undefined" \x26\x26 dojoConfig.locale || null, packages: [{ name: "dojo", location: "./dojo" }, { name: "dijit", location: "./dijit" }, { name: "dojox", location: "./dojox" }, { name: "dgrid1", location: "./dgrid1" }, { name: "dstore", location: "./dstore" }, { name: "xstyle", location: "./xstyle" }, { name: "esri", location: "./esri" }, { name: "moment", location: "./moment", main: "moment/moment" }] }'}};
return e});