// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/raster/ImageServiceRaster","require dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/config dojo/_base/json dojo/sniff dojo/DeferredList dojo/when ../../../kernel ../../../Evented ../../../request ../../../geometry/Extent ../../../geometry/Point ../../../SpatialReference ../../../deferredUtils ../../../urlUtils ../../MosaicRule ../../ImageServiceParameters ../../PixelBlock ./RasterInfo ./BasicRaster ../../rasterFormats/rasterCodec ../tile/RasterTileInfo".split(" "),
function(n,r,k,e,B,C,f,t,u,v,w,D,h,p,x,E,m,F,q,G,H,y,z,I,A){n=r([z],{declaredClass:"esri.layers.rasterLib.raster.ImageServiceRaster",sourceType:"ImageService",constructor:function(a){a&&(this._imageServiceParams=a.imageServiceParameters,this._commonReqParams=a._commonReqParams,this._imageServiceParams||(this._imageServiceParams={interpolation:a.interpolation,pixelType:a.pixelType,format:a.format||"lerc",compressionQuality:a.compressionQuality,bandIds:a.bandIds,noDataInterpretation:a.noDataInterpretation,
adjustAspectRatio:a.adjustAspectRatio,mosaicRule:a.mosaicRule,renderingRule:a.interpolation}))},open:function(){var a=new e;if(this.serviceInfo&&this.rasterInfo)return this.loaded=!0,this._findCredential(),this.setFetchParameters(this._imageServiceParams),a.resolve(this),a.promise;var b=this.serviceInfo||this._generateServiceInfo(this._imageServiceParams&&this._imageServiceParams.renderingRule),c=k.hitch(this,function(b){this.serviceInfo=b;this._findCredential();var c=this._parseRasterInfo(b),d={};
b.defaultMosaicMethod?(d.method=b.defaultMosaicMethod,d.operation=b.mosaicOperator,d.sortField=b.sortField,d.sortValue=b.sortValue):d.method=q.METHOD_NONE;this.serviceInfo.defaultMosaicRule=new q(d);this.serviceInfo.defaultMosaicRule.ascending=!0;b=this._getColormap(this);var d=this._getHistograms(this),g=this._getRasterAttributeTable(this),e=this._getKeyProperties(this),f=this._getMultidimensionalInfo(),h=this._getSlices();(new u([b,d,g,e,f,h])).then(k.hitch(this,function(b){b[0][0]&&(c.colormap=
b[0][1]);b[1][0]&&(c.histograms=b[1][1]);b[2][0]&&(c.vat=b[2][1]);b[3][0]&&(c.keyProperties=b[3][1]);b[4][0]&&(c.multidimensionalInfo=b[4][1]);this._slices=b[5][0]?b[5][1]:null;c.keyProperties&&c.keyProperties.DataType&&(this.dataType=c.keyProperties.DataType);this.loaded=!0;this.rasterInfo=c;this.setFetchParameters(this._imageServiceParams);a.resolve(this)}))}),d=k.hitch(this,function(b){this.loaded=!0;a.reject(b)});v(b,c,d);return a.promise},setFetchParameters:function(a,b){if(b)this.imageServiceParams=
a;else{var c=this.imageServiceParams;c&&a?Object.keys(a).forEach(function(b){c[b]=a[b]}):this.imageServiceParams=a}this._constructGetImageParams();this._getRasterIdentifier(!0)},read:function(a){if(a.pixelBlock||a.texture){var b=new e;b.resolve(a);return b.promise}if(!1===a.virtual&&this.tileInfo&&!this.tileInfo.virtual)return this.readTile(a);var c=a.extent,d=c.spatialReference.wkid||f.toJson(c.spatialReference.toJson(!1)),g=a.timeExtent?a.timeExtent.toJson().join(","):null,b=this.url+"/exportImage",
l={};this._slices&&(l.sliceid=this.sliceId||0);this.disableClientCaching&&(l._ts=(new Date).getTime());c=k.mixin({},this._commonReqParams,{bbox:c.xmin+","+c.ymin+","+c.xmax+","+c.ymax,imageSR:d,bboxSR:d,size:a.width+","+a.height,time:g},l);return this._requestPixels({url:b,payload:c,decodeParams:{width:a.width,height:a.height,planes:null,pixelType:null,format:null,decodeFunc:null,isPoint:!1},tileOptions:a})},readTile:function(a){var b=this.tileBoundary&&this.tileBoundary[a.level];if(b&&(b.minRow>
a.row||b.maxRow<a.row||b.minCol>a.col||b.maxCol<a.col))return b=new e,b.resolve(a),b.promise;var b=this.url+"/tile/"+a.level+"/"+a.row+"/"+a.col,c={width:this.tileInfo.cols,height:this.tileInfo.rows,planes:null,pixelType:null,format:null,decodeFunc:null,isPoint:"elevation"===a.tileType.toLowerCase()?!0:!1},d=this._slices?"sliceid\x3d"+(this.sliceId||0)+"\x26":"",d=this.disableClientCaching?"_ts\x3d "+(new Date).getTime():d.replace(/&$/,"");return this._requestPixels({url:b+(0<d.length?"?"+d:""),payload:{},
decodeParams:c,tileOptions:a})},toJson:function(){return{url:this.url,tileInfo:this.tileInfo,rasterInfo:this.rasterInfo,serviceInfo:this.serviceInfo,sourceType:this.sourceType,_commonReqParams:this._commonReqParams,_rasterId:this._rasterId}},getSliceIndex:function(a){var b=null;if(null==this._slices||null==a)return 0;for(var c=0;c<this._slices.length;c++){var d=this._slices[c].multidimensionalDefinition;if(d.length===a.length&&!d.some(function(b){var c=a.filter(function(a){return b.variableName===
a.variableName&&a.dimensionName===b.dimensionName})[0];if(!c)return!0;var d=Array.isArray(b.values[0])?b.values[0][0]:b.values[0],c=Array.isArray(c.values[0])?c.values[0][0]:c.values[0];return d!==c})){b=c;break}}return b},_generateServiceInfo:function(a){var b=this.url,c=new e(m._dfdCanceller);c._pendingDfd=h({url:b,content:{f:"json",renderingRule:a?f.toJson(a.toJson()):null},handleAs:"json",callbackParamName:"callback"});c._pendingDfd.then(function(a){c.callback(a)},function(a){c.errback(a)});return c},
_parseRasterInfo:function(a){var b=new y;b.bandCount=a.bandCount;b.extent=new p(a.fullExtent);b.spatialReference=a.spatialReference;b.pixelType=a.pixelType;b.width=Math.floor((a.fullExtent.xmax-a.fullExtent.xmin)/a.pixelSizeX+.5);b.height=Math.floor((a.fullExtent.ymax-a.fullExtent.ymin)/a.pixelSizeY+.5);b.cellSize=new x({x:a.pixelSizeX,y:a.pixelSizeY,spatialReference:a.spatialReference});var c,d;if(a.minValues&&0<a.minValues.length&&a.maxValues&&a.stdvValues&&a.meanValues){c=[];for(d=0;d<a.minValues.length;d++)c.push({min:a.minValues[d],
max:a.maxValues[d],mean:a.meanValues[d],stddev:a.stdvValues[d]});a.bandCount!==c.length&&(c=null)}this.dataType=a.serviceDataType?a.serviceDataType.replace("esriImageServiceDataType",""):"Generic";b.statistics=c;a.objectIdField&&a.fields&&(b.catalogInfo={objectIdField:a.objectIdField,fields:a.fields});b.timeInfo=a.timeInfo;if(a.tileInfo){this.tileInfo=new A(a.tileInfo);this.tileInfo.tileType=a.cacheType||"Map";b.tileInfo=this.tileInfo;var g=b.extent,l=this.tileInfo.origin,e=this.tileInfo.cols,f=this.tileInfo.rows;
this.tileBoundary=this.tileInfo.lods.map(function(a){return{minCol:Math.floor((g.xmin-l.x+.1*a.resolution)/e/a.resolution),maxCol:Math.floor((g.xmax-l.x-.1*a.resolution)/e/a.resolution),minRow:Math.floor((l.y-g.ymax+.1*a.resolution)/f/a.resolution),maxRow:Math.floor((l.y-g.ymin-.1*a.resolution)/f/a.resolution)}})}return b},_getColormap:function(a){a=this.url+"/colormap";var b=new e(m._dfdCanceller),c={f:"json"},d=this.serviceInfo.hasColormap||this.rasterInfo&&this.rasterInfo.hasColormap;10<this.serviceInfo.currentVersion&&
d?(b._pendingDfd=h({url:a,content:c,handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(function(a){b.callback(a.colormap)},function(a){b.errback(a)})):b.callback(null);return b},_getHistograms:function(a){var b=this.url+"/histograms",c=new e(m._dfdCanceller),d={f:"json"},g=this.serviceInfo.hasHistograms||this.rasterInfo&&this.rasterInfo.hasHistograms;a&&a.renderingRule&&(d.renderingRule=f.toJson(a.renderingRule.toJson()),g=!0);10<this.serviceInfo.currentVersion&&g?(c._pendingDfd=h({url:b,
content:d,handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(a){c.callback(a.histograms)},function(a){c.errback(a)})):c.callback(null);return c},_getRasterAttributeTable:function(a){var b=this.url+"/rasterAttributeTable",c=new e(m._dfdCanceller),d={f:"json"},g=this.serviceInfo.hasRasterAttributeTable;a&&a.renderingRule&&(d.renderingRule=f.toJson(a.renderingRule.toJson()),g=!0);10<this.serviceInfo.currentVersion&&g?(c._pendingDfd=h({url:b,content:d,handleAs:"json",callbackParamName:"callback"}),
c._pendingDfd.then(function(a){c.callback(a)},function(a){c.errback(a)})):c.callback(null);return c},_getKeyProperties:function(a){var b=this.url+"/keyProperties",c=new e(m._dfdCanceller),d={f:"json"};a&&a.renderingRule&&(d.renderingRule=f.toJson(a.renderingRule.toJson()));10<this.serviceInfo.currentVersion?(c._pendingDfd=h({url:b,content:d,handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(a){c.callback(a)},function(a){c.errback(a)})):c.callback(null);return c},_getMultidimensionalInfo:function(){var a=
this.url+"/multidimensionalInfo",b=new e(m._dfdCanceller);10.3<=this.serviceInfo.currentVersion&&this.serviceInfo.hasMultidimensions?(b._pendingDfd=h({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(k.hitch(this,function(a){b.callback(a.multidimensionalInfo)}),function(a){b.errback(a)})):b.callback(null);return b},_getSlices:function(){var a=this.url+"/slices",b=new e(m._dfdCanceller);this.serviceInfo.hasMultidimensions?(b._pendingDfd=h({url:a,content:{f:"json"},
handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(k.hitch(this,function(a){b.callback(a.slices)}),function(a){b.errback(a)})):b.callback(null);return b},_initializationFailed:function(){},_constructGetImageParams:function(){var a=this.imageServiceParams||{},b=k.mixin({},this._query,{f:"image",interpolation:a.interpolation,pixelType:a.pixelType,format:a.format||"lerc",compressionQuality:a.compressionQuality,bandIds:a.bandIds?a.bandIds.join(","):null,noData:null!=a.noData?a.noData.join(","):
null,noDataInterpretation:a.noDataInterpretation,adjustAspectRatio:null==a.adjustAspectRatio?null:a.adjustAspectRatio,mosaicRule:a.mosaicRule?f.toJson(a.mosaicRule.toJson()):null,renderingRule:a.renderingRule?f.toJson(a.renderingRule.toJson()):null,token:this.credential&&this.credential.token||null});"lerc"===b.format.toLowerCase()?(b.compressionTolerance=a.compressionTolerance,10.5<=this.serviceInfo.currentVersion&&(b.lercVersion=a.lercVersion||2)):"tiff"===b.format.toLowerCase()?b.compression=a.compression:
-1<["jpg","jpeg","jpg","jpgpng"].indexOf(b.format.toLowerCase())&&(b.compression=a.compression);this._commonReqParams=b},_getRasterIdentifier:function(a){if(this._rasterId)return this._rasterId;a=this.url.replace("http:","").replace("https:","");var b=[],c=this.imageServiceParams||{};b.push(a);b.push(c.interpolation);b.push(c.pixelType);b.push(c.compressionQuality);b.push(c.bandIds?c.bandIds.join(","):"");b.push(c.mosaicRule?f.toJson(c.mosaicRule.toJson()):"");b.push(c.renderingRule?f.toJson(c.renderingRule.toJson()):
"");a=b.join("|");return this._rasterId=this._computeSignature(a)},_wrapExtent:function(a){var b=a.spatialReference._getInfo(),c;if(b){var d=b.valid[0],b=b.valid[1];if(a.xmin<d-this.resolution.x||a.xmax>b+this.resolution.y)c=new p((a.xmin-d)%(b-d),a.ymin,(a.xmax-b)%(b-d),a.ymax,a.spatialReference),c.xmax<c.xmin&&(c=null)}return c||a}});t("extend-esri")&&k.setObject("layers.rasterLib.raster.ImageServiceRaster",n,w);return n});