// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/infographicPanels/Prizm5","dojo/_base/declare dojo/on dojo/dom-class dojo/dom-construct dojox/html/entities ../BaseWidget ../infographicUtils/dom ../infographicUtils/formatVariable ./supportClasses/Prizm5Data ../utils/ObjectUtil dojo/i18n!esri/nls/jsapi".split(" "),function(r,p,g,f,t,u,q,v,w,x,k){k=k.geoenrichment.dijit.Prizm5;return r(u,{baseClass:"Infographics_Prizm5",_mainTable:null,_detailsTable:null,_noSegmentsDiv:null,_openRowIndex:-1,createUIExpanded:function(a){this.inherited(arguments);
this._createUI(a)},createUICollapsed:function(a){this.inherited(arguments);this._createUI(a)},_createUI:function(a){this._mainTable=a.addContent("table",{"class":"Prizm5_Main_Table"});q.createCols(this._mainTable,[.25,.4,.35])},updateUIExpanded:function(){this.inherited(arguments);this._updateUI()},updateUICollapsed:function(){this.inherited(arguments);this._updateUI()},_updateUI:function(){var a=this;this._toMainView();for(var b=this._get3DominantSegementsInfo(),l=this._mainTable;l.rows.length;)l.deleteRow(-1);
b.length?b.forEach(function(c,b){function h(){e=d.insertCell(-1)}var d,e;d=l.insertRow(-1);d._info=c;p(d,"click",function(){a._toDetailViewForRow(d,b)});g.add(d,"Prizm5_LifeStyle");h();g.add(e,"Prizm5_LifeStyle_Image");var n=f.create("div",null,e);n.style.backgroundImage="url("+c.imageUrl+")";n.style.borderColor=c.color;f.create("span",{"class":"Prizm5_LifeStyle_Image_Code",innerHTML:c.code},n).style.borderColor=c.color;h();g.add(e,"Prizm5_Main_Name");e.innerHTML="\x3cspan class\x3d'Prizm5_Main_Label'\x3e"+
c.alias+"\x3c/span\x3e\x3cbr\x3e\x3cspan class\x3d'Prizm5_Main_Value'\x3e"+x.formatNumber(c.value)+" "+k.hhLabel+"\x3c/span\x3e";h();g.add(e,"Prizm5_Main_Pct");e.innerHTML="\x3cspan class\x3d'Prizm5_Main_Pct_Value'\x3e"+v({units:"pct",decimals:1},c.percentValue)+"\x3c/span\x3e\x3cbr\x3e\x3cspan class\x3d'Prizm5_Main_Pct_Label'\x3e"+k.prtHhLabel+"\x3c/span\x3e";h();g.add(e,"Prizm5_Main_Arrow");f.create("div",null,e)}):this._showNoSegementsInfo()},_get3DominantSegementsInfo:function(){for(var a=[],
b=this._getDataManager(),f=this.getValueByName(0,b.getTotalFieldName(this.data.features[0].attributes),!0),c=0;c<b.getNumClassifiedSegments();c++){var g=b.getFieldNameByIndex(c,this.data.features[0].attributes),h=this.getValueByName(0,g,!0);if(h){var d=b.getSegmentInfoByIndex(c);a.push({index:c,code:d.code,alias:d.alias,fieldName:g,value:h,percentValue:h/f*100,color:d.color,fields:d.fields,imageUrl:d.imageUrl})}}a.sort(function(a,b){return b.value-a.value});a.length=Math.min(a.length,3);return a},
_toDetailViewForRow:function(a,b){this._openRowIndex===b?(this._openRowIndex=-1,this._toMainView()):(this._openRowIndex=b,this._toDetailView(a,a._info))},_toMainView:function(){for(var a=0;a<this._mainTable.rows.length;a++)g.remove(this._mainTable.rows[a],"clicked");this._detailsTableRow&&(f.destroy(this._detailsTableRow),this._detailsTableRow=this._detailsTable=null);this._noSegmentsDiv&&f.destroy(this._noSegmentsDiv);this._noSegmentsDiv=null},_toDetailView:function(a,b){this._toMainView();g.add(a,
"clicked");this._createDetailsTable(a);this._createDetailedViewExpanded(b)},_createDetailsTable:function(a){this._detailsTableRow=f.create("tr",null,a,"after");a=f.create("td",{colSpan:"4"},this._detailsTableRow);this._detailsTable=f.create("table",{"class":"Prizm5_Details_Table"},a);q.createCols(this._detailsTable,[.5,.5])},_createDetailedViewExpanded:function(a){function b(a,b,c){var d={};a&&(d["class"]=a);b&&(d.innerHTML=t.encode(b));return f.create("div",d,c||m)}var l=this._detailsTable,c,m;a.fields.forEach(function(a,
e){0===e%2&&(c=l.insertRow(-1));e=a.label;a=a.value;m=c.insertCell(-1);g.add(m,"Prizm5_Details_FieldCell");var d=b("Prizm5_Details_FieldCellContent");b("Prizm5_Details_Label",e,d);b("Prizm5_Details_SubLabel",a,d)});c=l.insertRow(-1);m=c.insertCell(-1);m.colSpan=2;b("Prizm5_Details_LinkIcon dijitInline");var h=b("Wizard_Link Prizm5_Details_Link dijitInline",k.viewFullSegmentProfile);p(h,"click",function(){window.open(this._getDataManager().getUrl(a.index),"_blank")}.bind(this))},isDetailedViewOpen:function(){return 0<=
this._openRowIndex},getOpenDetailedViewRowIndex:function(){return this._openRowIndex},openDetailedViewAt:function(a){this._toDetailViewForRow(this._mainTable.rows[a],a)},collapseContent:function(){this._openRowIndex=-1;this._toMainView()},_showNoSegementsInfo:function(){this._noSegmentsDiv=f.create("div",{"class":"esriGEAbsoluteStretched esriGEContentVerticalAlignMiddle Prizm5_noSegmentsDiv",innerHTML:k.noSegmentsFound},this._mainTable,"after")},_getDataManager:function(){return w.getDataManagerByAttributes(this.data.features[0].attributes)}})});