// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/ColorRampSelector","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/i18n!../nls/jsapi dojo/store/Memory dojo/has ../kernel ../renderers/colorRampUtils dijit/form/FilteringSelect dojo/query dojo/dom-style dojo/on dojo/dom-construct".split(" "),function(k,d,f,n,p,e,q,h,g,l,m,r,t){g=k([g],{declaredClass:"esri.dijit.ColorRampSelector",_colorRampNameMap:null,_colorRamps:null,_namesShown:!1,colorRamp:null,constructor:function(a){k.safeMixin(this,a);this._i18n=n.widgets.colorRampSelector;
this._colorRamps=d.clone(h.predefinedColorRamps);this._colorRampNameMap=d.clone(h.predefinedColorRampNameMap)},startup:function(){this.inherited(arguments);this._styleDijitInput();this._setupColorRampList();this._setupDropdownEvents();this._handleColorRampChange();this._setColorRamp()},_setupDropdownEvents:function(){r(this.inputContainer,"click",d.hitch(this,this.toggleDropDown));this.dropDownEventsSetup=!0},_setColorRamp:function(){var a=this.colorRamp;a&&!this.setSelected(a)&&(this.addColorRamp(a),
this.setSelected(a))},_setupColorRampList:function(){this._generateColorRamps();this._populateColorRampList()},_styleDijitInput:function(){var a=l(".dijitReset.dijitInputInner",this.domNode)[0];this.inputContainer=l(".dijitReset.dijitInputField.dijitInputContainer",this.domNode)[0];m.set(this.inputContainer,"height","25px!important");m.set(a,"display","none")},_generateColorRamps:function(){var a=this._i18n.colorRamps,b;f.forEach(this._colorRamps,function(c){"none"===c.id?c.label="\x3chtml\x3e\x3cbody\x3e\x3cdiv style\x3d'padding: 5px 0px 5px 2px; font-weight: 700;'\x3e"+
a[c.id]+"\x3c/div\x3e\x3c/body\x3e\x3c/html\x3e":(c.name=a[c.id]||c.name,9>=e("ie")?(c.labelGradient="\x3chtml\x3e\x3cbody\x3e\x3clabel style\x3d'display: block; padding: 4px 0px 0px 4px;'\x3e"+c.name+"\x3c/label\x3e\x3c/body\x3e\x3c/html\x3e",c.label=c.labelGradient):(b=this._generateColorRampDivs(c),c.labelGradient="\x3chtml\x3e\x3cbody\x3e\x3cdiv title\x3d'"+c.name+"' style\x3d'height:20px; padding: 2px; direction: ltr!important;'\x3e"+b+"\x3c/div\x3e\x3c/body\x3e\x3c/html\x3e",c.label=this._namesShown?
"\x3chtml\x3e\x3cbody\x3e\x3clabel style\x3d'display: block; padding-left: 2px;'\x3e"+c.name+"\x3c/label\x3e\x3cdiv style\x3d'height:20px; padding: 2px; direction: ltr!important;'\x3e"+b+"\x3c/div\x3e\x3c/body\x3e\x3c/html\x3e":c.labelGradient))},this)},_populateColorRampList:function(){this.set("labelAttr","label");this.set("labelType","html");this.set("searchAttr","id");this.set("store",new p({data:this._colorRamps}));this._handleColorRampChange()},_generateColorRampDivs:function(a){if(a){var b,
c="";"multipart"===a.type?(b=100/a.colorRamps.length,f.forEach(a.colorRamps,function(a){c+=this._generateSingleGradientDiv(a.fromColor,a.toColor,b)},this)):c=this._generateSingleGradientDiv(a.fromColor,a.toColor,100);return c}},_generateSingleGradientDiv:function(a,b,c){if(a&&b){var d,e="";a=a.toRgb?a.toRgb():a;b=b.toRgb?b.toRgb():b;d="(90deg, rgb("+a.slice(0,3).join()+"), rgb("+b.slice(0,3).join()+"));";f.forEach(["-webkit-linear-gradient","-o-linear-gradient","-moz-linear-gradient","linear-gradient"],
function(a){e+="background: "+a+d});return"\x3cdiv style\x3d' display: inline-block; width:"+c+"%; padding: 0; height: 100%;"+e+"'\x3e\x3c/div\x3e"}},onChange:function(){this.inherited(arguments);this._handleColorRampChange()},_handleColorRampChange:function(){if(this.inputContainer){var a;f.some(this._colorRamps,function(b){if(b.id===this.value)return a=b,!0},this)&&("none"===this.value||9>=e("ie")?this.inputContainer.innerHTML="\x3chtml\x3e\x3cbody\x3e\x3cdiv style\x3d'padding: 4px 0px 0px 4px; font-weight: 400;'\x3e"+
t.toDom(a.label).innerHTML+"\x3c/div\x3e\x3c/body\x3e\x3c/html\x3e":this.inputContainer.innerHTML=a.labelGradient,"none"===a.id?this.colorRamp=this.colorRampName=null:(this.colorRampName=this._getColorRampName(a.id),this.colorRamp=a))}},_getColorRampName:function(a){var b;f.some(this._colorRampNameMap,function(c){if(c.id===a)return b=c.name,!0});return b},_getIndexById:function(a,b){return a.map(function(a){return a.id}).indexOf(b)},showNames:function(a){this._namesShown=a;this._setupColorRampList()},
reset:function(){this.set("value","none",!1);this._handleColorRampChange()},removeColorRamp:function(a){a&&this.store&&this.store.data&&this.store.data.length&&this.store.remove(a.id)},addColorRamp:function(a){if(a){if(9>=e("ie"))a.labelGradient="\x3clabel style\x3d'display: block; padding: 4px 0px 0px 4px;'\x3e"+a.name+"\x3c/label\x3e",a.label=a.labelGradient;else{var b=this._generateColorRampDivs(a);a.labelGradient="\x3cdiv title\x3d'"+a.name+"' style\x3d'height:18px; padding: 1px; direction: "+
(this.reverseRamp?"rtl":"ltr")+"!important;'\x3e"+b+"\x3c/div\x3e";a.label=this._namesShown?"\x3clabel style\x3d'display: block; padding-left: 2px;'\x3e"+a.name+"\x3c/label\x3e\x3cdiv style\x3d'height:18px; padding: 1px; direction: ltr!important;'\x3e"+b+"\x3c/div\x3e":a.labelGradient}this.store&&this.store.data&&this.store.data.length?this.store.put(a,{overwrite:!0}):(b=this._getIndexById(this._colorRamps,a.id),-1<b&&this._colorRamps.splice(b,1),this._colorRamps.push(a));b=this._getIndexById(this._colorRampNameMap,
a.id);-1<b&&this._colorRampNameMap.splice(b,1);this._colorRampNameMap.push({id:a.id,name:a.name})}},setSelected:function(a,b){if(!a)return this.reset();if(a=h.getColorRampId(a,this._colorRamps,this._colorRampNameMap))return this.set("value",a,!1),this._handleColorRampChange(a),!0;this.reset();return!1}});e("extend-esri")&&d.setObject("dijit.ColorRampSelector",g,q);return g});