// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/renderer/rasterRendererHelper","dojo/_base/declare dojo/_base/lang ../../PixelBlock ./RasterColormapRenderer ./RasterUniqueValueRenderer ./RasterRGBRenderer ./RasterStretchColorRampRenderer ./RasterClassBreaksRenderer ./RasterShadedReliefRenderer".split(" "),function(v,w,x,n,p,q,r,t,u){var m=function(){function a(a){b[a.prototype.rendererName]=a}var b={};a(n);a(q);a(r);a(p);a(t);a(u);return b}();return{wellKnownRenderers:m,isSupported:function(a){if(!a)return!1;var b=
!0;m[a.rendererName]||(b=!1);return b},create:function(a){if(!a)return null;var b;a.rendererName?(b=a.rendererName,a=a.rendererArguments):(b="uniqueValue rasterStretch rasterShadedRelief rgb rasterColormap classBreaks".split(" ").indexOf(a.type),b="UniqueValue Stretch ShadedRelief RGB Colormap ClassBreaks".split(" ")[b],"rasterStretch"===a.type&&a.bandIndex&&1<a.bandIndex.length&&(b="RGB"));return(b=m[b])?new b(a):null},createDefaultRenderer:function(a){if(a&&a.raster){var b=a.raster.rasterInfo,d=
a.raster.dataType;if(b){var c=a.raster.rasterFunction,e=["Stretch","Colormap","ContrastAndBrightness"];if(c&&"U8"===b.pixelType&&-1<e.indexOf(c.functionName))c.renderTexture=!0;else if("Processed"!==d||!(a.useWebGL&&c&&c.renderTexture||!a.useWebGL&&"U8"===b.pixelType)){c&&(b=c.rasterInfo);var c=b.bandCount,f=b.colormap,g=b.vat,e=b.histograms,k;e&&0===e.length&&(e=null);var h=b.statistics&&b.statistics.map(function(a){return[a.min,a.max,a.mean,a.stddev]});if(1===c&&f&&0<f.length)k=this._getDefaultColormapRenderer(g,
f);else if(1===c&&g&&g.features&&0<g.features.length)k=new p({});else{f=0;g=!1;d||!a.raster||!a.raster.tileInfo||void 0!==a.raster.tileInfo.tileType&&"Map"!==a.raster.tileInfo.tileType?"U8"===b.pixelType&&"Processed"===d?(f=5,h=h||[[0,255,0,0],[0,255,0,0],[0,255,0,0]],g=!1):"U8"===b.pixelType||"Elevation"===d?(f=5,g=h?!1:!0):"Scientific"===d?(f=5,g=h?!1:!0,k=this._getDefaultScientificColorRamp()):e&&0<e.length?(f=6,g=!1):h?(f=5,g=!1):(f=6,g=!0):(h=[[0,255,0,0],[0,255,0,0],[0,255,0,0]],f=5,g=!1);h||
(f=5,g=!0);var l;3<=c&&!(a.bandIds||a.raster&&a.raster.imageServiceParams&&a.raster.imageServiceParams.bandIds)&&(l=this.getDefaultBandCombination(b));2===c&&(l=[0,0,0]);l&&(h=l.map(function(a){return h[a]}));a={stretchType:f,min:0,max:255,dra:g,minPercent:.25,maxPercent:.25,useGamma:!1,computeGamma:!1,statistics:h,histograms:e,numberOfStandardDeviations:2.5,bandIndex:l};1===c?(k&&(a.colorRamp=k,a.invert=!1),k=new r(a)):k=new q(a)}return k}}}},getDefaultBandCombination:function(a){var b=a.bandCount;
if(1===b)return null;if(2===b)return[0];a=a.keyProperties&&a.keyProperties.BandProperties;var d;if(a&&a.length===b){var c=this.getWellKnownBandIndexes(a);a=c.red;var e=c.green,f=c.blue,c=c.nir;null!=a&&null!=e&&null!=f?d=[a,e,f]:null!=c&&null!=a&&null!=e&&(d=[c,a,e])}!d&&3<=b&&(d=[0,1,2]);return d},getWellKnownBandIndexes:function(a){for(var b={},d=0;d<a.length;d++){var c=a[d],e=c.BandName&&c.BandName.toLowerCase();"red"===e?b.red=d:"green"===e?b.green=d:"blue"===e?b.blue=d:"nearinfrared"===e||"nearinfrared_1"===
e||"nir"===e?b.nir=d:c.WavelengthMax&&c.WavelengthMin&&(e=c.WavelengthMin,c=c.WavelengthMax,null==b.blue&&410<=e&&480>=e&&480<=c&&540>=c?b.blue=d:null==b.green&&490<=e&&560>=e&&560<=c&&610>=c?b.green=d:null==b.red&&595<=e&&670>=e&&660<=c&&730>=c?b.red=d:null==b.nir&&700<=e&&860>=e&&800<=c&&950>=c&&(b.nir=d))}return b},_getDefaultColormapRenderer:function(a,b){if(b||b.length){var d=[],c=this._ratContainsColormap(a);if(c)var e=this._getRATValueClassNameMap(a);b.forEach(function(a){var b=e?e[a[0]]:a[0];
d.push({color:[a[1],a[2],a[3]],value:a[0],label:c?null!=b?b:"":a[0]})});return new n({colormapInfos:d})}},_ratContainsColormap:function(a){if(!a||!a.fields)return!1;var b,d,c;return a.fields.some(function(a){a&&a.name&&(a=a.name.toLowerCase(),"red"===a&&(b=!0),"green"===a&&(d=!0),"blue"===a&&(c=!0));return b&&d&&c})},_getRATValueClassNameMap:function(a){if(!a||!a.fields)return null;var b={},d,c;a.fields.forEach(function(a){if("classname"===a.name.toLowerCase()||"class_name"===a.name.toLowerCase())d=
a.name;"value"===a.name.toLowerCase()&&(c=a.name)});a.features.forEach(function(a){a=a.attributes;b[a[c]]=d?a[d]:a[c]});return b},_getDefaultScientificColorRamp:function(){return{type:"multipart",colorRamps:[{fromColor:[255,0,0],toColor:[255,255,0]},{fromColor:[255,255,0],toColor:[0,255,255]},{fromColor:[0,255,255],toColor:[0,0,255]}].map(function(a){return{fromColor:a.toColor,toColor:a.fromColor}}).reverse()}}}});