// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_ColumnBarChartSeriesCalculator","dojo/_base/lang ../../ChartTypes ../../ChartSorting ../../ChartLineStyles ../../ThemeCalculator ../../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../utils/TooltipInfoBuilder ./_ComparisonUtil ./_AxisBuilder ./_PointLabelUtil ./_StatsBuilder esri/dijit/geoenrichment/utils/ColorUtil".split(" "),function(I,J,v,w,A,K,L,M,x,B,N,G){var O={calcLineStyle:function(a,d){return{color:G.getColorWithAlpha(d.outlineColor||
a,d.outlineOpacity),width:d.outlineThickness,style:w.toGFXValue(d.outlineStyle||w.SOLID)}}};return{calcSeriesColumnBar:function(a){var d=a.chart,e=a.visualProperties,g=a.seriesItems,w=1===g.length,p=a.seriesItemsWithComparison||g,l=a.chartType,E=a.comparisonInfo,C=a.themeSettings,q=a.viewModel,r=1===p.length&&a.sorting,P=1<p.length&&e.renderColumnBarsInOppositeDirections,t=[],H=new N({visualProperties:e,seriesItems:p,viewModel:q,currentFeatureIndex:a.currentFeatureIndex,isMultiFeatureChart:a.isMultiFeatureChart,
excludedSeriesHash:a.excludedSeriesHash,comparisonFeatureAttributes:a.comparisonFeatureAttributes,chartType:l});B.createPointToLabelMap(d);var F={};p.forEach(function(f,g){if(f.points.length){var y={name:f.label,data:[],isComparisonSeries:f.isComparisonSeries,params:{plot:f.isComparisonSeries&&M.getComparisonPlotName(l,E)||void 0}},c=H.getStatisticsForSeriesAt(g);A.provideMissingIconsForPoints(f.points,l);var x=[];f.points.forEach(function(b,m){var d=c.values[m],D=d.value,h=D||0,k;if(e.conditionalStyling){var u=
K.getConditionalStyle(d.isBenchmarked?d.ownValue:h,e.conditionalStyling);k=u&&u.backgroundColor}k=k||A.calcColorForPoint({point:b,seriesItem:f,pointIndex:m,seriesIndex:g,numSeries:w?1:p.length,chartType:l,themeSettings:C,isComparisonSeries:f.isComparisonSeries,comparisonInfo:E,isMultiFeature:a.isMultiFeatureChart});var z=O.calcLineStyle(k,e),r=k;k=1>e.columnBarOpacity?G.getColorWithAlpha(k,e.columnBarOpacity):k;var n;b.hidden&&(n=k,k=r="transparent");var t;b.hidden&&(t=z.color,z.color="transparent");
u=m+1;h={x:u,y:h*function(){if(P){var b=!a.isMultiFeatureChart&&J.isBarLike(l);return g>=p.length/2?b?1:-1:b?-1:1}return 1}(),originalValue:D,isUnavailableData:isNaN(D),valueProp:"y",unsortedIndex:m,originalIndex:b.originalIndex||m,seriesIndex:g,name:B.getPointLabel(b,q),valuesSumsInSeries:c.absSumInSeries,point:b,fill:k,icon:A.calcIconForPoint(b,r,l),bgIcon:A.calcBackgroundIconForPoint(b,l,C,e),stroke:{color:z.color,width:z.width,style:z.style},unhiddenFillColor:n,unhiddenLineColor:t,isBenchmarked:d.isBenchmarked,
unbenchmarkedValue:d.ownValue};e.isStacked&&(n=e.showValuesAsWeightInStack?c.stackValuesAsWeighedPercents:c.stackValues,h.stackValues=n&&n[m]);e.showValuesAsWeightInStack?h.y=c.weightsInStack?100*c.weightsInStack[m]:0:e.yAxis.showValuesAsWeightsInSeries&&(h.y/=c.absSumInSeries/100);n=B.getPointLabel(p[0].points[m]||b,q);b=L.getTooltipInfo({yValue:D,pointLabel:n,seriesLabel:f.label,isSinglePointInSeries:1===f.points.length,minInSeriesValue:c.minInSeries,maxInSeriesValue:c.maxInSeries,sumInSeriesValue:c.sumInSeries,
absSumInSeriesValue:c.absSumInSeries,avgInSeriesValue:c.avgInSeries,weightInStack:c.weightsInStack&&c.weightsInStack[m],minInAreasValue:c.minInSeries,maxInAreasValue:c.maxInSeries,sumInAreasValue:c.sumInSeries,absSumInAreasValue:c.absSumInSeries,avgInAreasValue:c.avgInSeries,visualProperties:e,chartType:l,isMultiFeature:a.isMultiFeatureChart,conditionalStyling:e.conditionalStyling,fieldInfo:b.fieldInfo,isThisAreaSpecific:E&&!a.isMultiFeatureChart?!f.isComparisonSeries:void 0,isThisAreaSingleSeries:w,
decimals:b.value&&b.value.decimals,fill:h.fill,stroke:0<h.stroke.width?h.stroke.color:void 0,isBenchmarked:d.isBenchmarked,unbenchmarkedValue:d.ownValue,chartContainer:a.chartContainer,viewModel:q,theme:a.theme,themeSettings:C,dataDrillingPanelInfo:a.dataDrillingPanelInfo,pointName:a.isMultiFeatureChart?f.label:n,seriesName:b.originalSeriesName||f.label,areaName:b.areaName,featureIndex:d.featureIndex,isComparisonPoint:b.isComparisonPoint,comparisonFeatureAttribute:b.comparisonFeatureAttribute});var v=
F[u]=F[u]||[];a.excludedSeriesHash[f.label]||(v.push(b),x.push(b));b.getGroup=function(){return a.isMultiFeatureChart?x:v};h.tooltip=b;y.data.push(h)});r&&r!==v.NONE&&(y.data.sort(function(a,c){return(a.y-c.y)*(r===v.DESC?-1:1)}),y.data.forEach(function(a,c){a.x=c+1}));y.data.forEach(function(a){B.updatePointIndexToLabelMap(d,a.x,g,a.point,q)});t.push(y)}},this);g=H.getTotalStats();x.prettifyYAxis(g.minYValue,g.maxYValue,d,e,l,C,q,t);a.plotStats&&(I.mixin(a.plotStats,g),a.plotStats.pointIndexToTooltipsHash=
F);return t},prettifyColumnBarYAxis:function(a){x.prettifyYAxis(a.totalStat.minYValue,a.totalStat.maxYValue,a.chart,a.visualProperties,a.chartType,a.themeSettings,a.viewModel,a.chartSeries,!0,a.chartSize);a.chart.dirty=!0}}});