// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/locator/LocatorPointsBuilder","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when esri/graphic esri/layers/GraphicsLayer esri/renderers/SimpleRenderer esri/renderers/jsonUtils esri/symbols/jsonUtils esri/geometry/jsonUtils esri/dijit/PopupTemplate esri/dijit/geoenrichment/ReportPlayer/config ./DefaultSymbolRenderer ../_HeatMapSupport ../LayerInfoLoader ../../Projector ../../symbols/HighlightedSymbolGenerator ../../../../../dataProvider/supportClasses/areas/AreasInfoTemplateBuilder dojo/i18n!esri/nls/jsapi".split(" "),
function(y,n,p,r,z,t,A,B,C,D,E,l,F,G,u,H,I,m){var J=y([z,F]);m=m.geoenrichment.dijit.ReportPlayer.ReportPlayer;var q={addLocatorPoints:function(a,d){function k(a){return-1===a.indexOf("'")?a:a.replace(f,'"')}var f=/'/g;a.locatorPointsControllers&&a.locatorPointsControllers.forEach(function(h){var b=h.getCalculatorDataArray();if(b&&b.length){var e=h.getRendererJson(a.calculatorFieldName),c=new J,f=e?A.fromJson(n.clone(e)):new t(l.getDefaultLocatorSymbol());c.setRenderer(f);var w=[],m=[],x=e?"simple"===
e.type&&B.fromJson(n.clone(e.symbol)):l.getDefaultLocatorSymbol();b.forEach(function(b,d){if(b.Point||b.Polygon){var e={},f,v,l=h.getVariableObjects().map(function(a,c){var d=a.fieldName.toLowerCase();-1!==d.indexOf("coname")&&(v=!0,f=a.fieldName);v||-1===d.indexOf("name")||(f=a.fieldName);f||0!==c||(f=a.fieldName);e[a.fieldName]=a.alias;return{label:a.alias,value:b[a.fieldName]}}),l=new D({title:"",fieldInfos:[],description:I.buildAttributesTable(null,l)}),g=n.mixin({},b);delete g.Point;delete g.Polygon;
g.__pointIndex=d;g.__nameField=f;g.__fieldAliases=e;d=C.fromJson(JSON.parse(k(b.Point||b.Polygon)));g=new r({attributes:g});u.needProject(d,a.map)?(w.push(g),m.push(d)):(g.setGeometry(d),c.add(g));x&&g.setSymbol(x);g.setInfoTemplate(l)}});q._registerLayer(c,a.map,h,a);d.registerLayerInfo({layer:c,type:d.LOCATOR_POINTS,preferredIndex:h.getLayerIndex(a.calculatorFieldName),geometryType:b[0].Point?"esriGeometryPoint":"esriGeometryPolygon"});q._provideNameForLayer(c,h,a);p(u.projectGeometries(m,a.map),
function(a){a.forEach(function(a,b){b=w[b];b.setGeometry(a);c.add(b)})})}})},_registerLayer:function(a,d,k,f){var h=k.getRendererJson(f.calculatorFieldName);H.getHighlightSymbol({rendererJson:h,defaultHighlightSymbol:l.getDefaultLocatorSymbolHighlighted(),graphicsLayer:a}).then(function(b){var e;b&&b.frameSymbol&&(e=new r,e.setSymbol(b.frameSymbol));k.setLocatorPointsLayer(f.calculatorFieldName,a,d,{getPointIndexForGraphicFunc:function(a){return a.attributes&&a.attributes.__pointIndex},getGraphicForPointAtFunc:function(b){var c;
a.graphics.some(function(a){if(a.attributes&&a.attributes.__pointIndex===b)return c=a,!0});return c},setGraphicHighlightedFunc:function(c,d){b&&(e&&a.remove(e),!d&&c.__isHighlighted?(c.setSymbol(c.__originalSymbol),delete c.__originalSymbol,delete c.__isHighlighted):d&&!c.__isHighlighted&&(c.__originalSymbol=c.symbol,c.__isHighlighted=!0,c.setSymbol(b.getSymbol?b.getSymbol(c):b.symbol),a.remove(c),e&&(e.setGeometry(c.geometry),a.add(e)),a.add(c)))}})})},_provideNameForLayer:function(a,d,k){var f=
d.getLayerUrl(),h=d.getLayerID();d=(d=d.getLayerName(k.calculatorFieldName))&&{name:d};f?p(!E.isPlayerOnServer&&(d||G.getInfo(f)),function(b){a.name=b&&b.name||m.locatorLayerLegendTitle;a.onVisibilityChange()}):p(d||k.geClient&&k.geClient.getLayerInfo(k.countryID,h),function(b){a.name=b&&b.name||m.locatorLayerLegendTitle;a.onVisibilityChange()})},getDefaultLocatorRenderer:function(){return new t(l.getDefaultLocatorSymbol())}};return q});