// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/commands/mapToImage/MapToURLUtil","require dojo/_base/declare esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when esri/dijit/geoenrichment/promise/all dojo/dom-style esri/dijit/geoenrichment/utils/DataUtil esri/dijit/geoenrichment/utils/ImageInfoUtil esri/dijit/geoenrichment/utils/RegExpUtil esri/dijit/geoenrichment/utils/UrlUtil".split(" "),function(z,A,n,m,B,r,C,D,p,E){function F(){var a=new n;z("esri/tasks/PrintTask esri/tasks/PrintParameters esri/tasks/PrintTemplate esri/layers/GraphicsLayer ./DotDensityToImageUtil ./LegendToLayerUtil".split(" "),
function(b,f,g,c,l,k){t=f;u=g;v=c;q=l;w=k;x=A(b,{returnJson:!1,mapName:null,_execute:function(){this.returnJson&&(this.printGp.submitJob=this.printGp.execute=function(a,b){a="data:application/json;base64,"+C.base64FromJson(a.Web_Map_as_JSON);b([{value:{url:a}}]);return(new n).resolve()});return this.inherited(arguments)},_getPrintDefinition:function(a,b){var d=this.inherited(arguments);this.returnJson&&this.mapName&&(d.title=this.mapName);console.log(d);return d},_createOperationalLayers:function(a,
b){var d=this.inherited(arguments);if(b.__legendLayerId){var f=d.filter(function(a){return a.id===b.__legendLayerId})[0];d.splice(d.indexOf(f),1);d.push(f)}return d},_createFeatureCollection:function(a,b,f,c){var d=this.inherited(arguments);this.returnJson&&d&&("esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.GraphicsLayer"===a.declaredClass)&&d.featureCollection.layers.forEach(function(b){b.layerDefinition.name=a.arcgisProps&&a.arcgisProps.title||
a._titleForLegend||a.name||a.id;b.layerDefinition.name=p.decodeXML(b.layerDefinition.name);b.layerDefinition.objectIdField="OBJECTID";b.layerDefinition.fields=[{name:"OBJECTID",type:"esriFieldTypeOID"}];var d={OBJECTID:1},f=/[^\w]/g,c;b.featureSet.features.forEach(function(a,k){a.attributes=a.attributes||{};a.attributes.OBJECTID=k+1+"";a.attributes.__nameField||(a.attributes.Name=p.decodeXML(a.attributes.Name||b.layerDefinition.name),c="Name");k=a.attributes.__fieldAliases;for(var g in a.attributes)if(0!==
g.indexOf("__")){var l=g,e=a.attributes[g];"string"===typeof e&&(e=p.decodeXML(e));var h=k&&k[g];(h=h&&h.replace(f,"_"))&&void 0===a.attributes[h]&&(a.attributes[h]=e,l=h);a.attributes.__nameField===g&&(c=l);d[g]||(d[g]=1,b.layerDefinition.fields.push({name:l,type:"string"===typeof e?"esriFieldTypeString":"esriFieldTypeDouble"}))}});b.layerDefinition.displayField=c});return d},_convertSvgSymbol:function(a){return a}});a.resolve()});return a.promise}var x,t,u,v,q,w,y,e={setPrintMapTaskUrl:function(a){y=
a;E.registerCORS(a)},mapToURL:function(a,b,f,g){var c=e._getUrlForMap(a);if(c)return c;c=F().then(function(){return e._replaceDotDensityLayersWithPictureMarkers(a).then(function(c){return m(b&&w.legendToGraphicsLayer(b,a,f),function(b){b&&a.addLayer(b);return m(e._runPrintTask(a,f,b,g),function(d){b&&a.removeLayer(b);e._rollbackReplacing(a,c);var f=new n;setTimeout(function(){f.resolve(d.url)},100);return f.promise})})})});e._putUrlToCache(a,c);return c},_replaceDotDensityLayersWithPictureMarkers:function(a){var b=
[];for(i=0;i<a.graphicsLayerIds.length;i++)layer=a.getLayer(a.graphicsLayerIds[i]),layer.loaded&&layer.visible&&q.isDotDensity(layer)&&b.push(e._createGraphicsLayerFromDotDensityLayer(i,layer,a));return B(b)},_createGraphicsLayerFromDotDensityLayer:function(a,b,f){return q.createPictureMarkersFromDotDensityLayer(b,f.extent,f).then(function(g){if(!g)return null;var c=new v;g.map(function(a){c.add(a)});f.addLayer(c,a);b.visible=!1;return{addedLayer:c,hiddenLayer:b}}).otherwise(function(a){console.log(a);
return null})},_runPrintTask:function(a,b,f,g){function c(){var c=new x(y);c.returnJson=g&&g.replaceWithJson;c.mapName=g&&g.mapName;var e=new t;e.map=a;var d=new u;d.exportOptions={width:3.125*r.get(b,"width"),height:3.125*r.get(b,"height"),dpi:300};d.format="png32";d.showAttribution=!1;d.forceFeatureAttributes=!0;d.__legendLayerId=f&&f.id;e.template=d;return c.execute(e)}return m(c(),function(a){return a},function(a){console.log(a);return m(c(),function(a){return a},function(a){console.log(a);return c()})})},
_rollbackReplacing:function(a,b){b.forEach(function(b){b&&b.addedLayer&&a.removeLayer(b.addedLayer);b&&b.hiddenLayer&&(b.hiddenLayer.visible=!0)})},urlToSrc:function(a,b){return b&&b.saveImagesAsDataUrl?D.getRemoteImageDataUrl(a,{sizeLimit:1500}):a}},h,G=0;e.enableCaching=function(){h={}};e.clearCaching=function(){h=null};e._putUrlToCache=function(a,b){h&&b&&(a.__mapToImageUtilKey=G++,h[a.__mapToImageUtilKey]=b)};e._getUrlForMap=function(a){return h&&h[a.__mapToImageUtilKey]};return e});