define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Definieer welke infographics er beschikbaar zijn in de widget:",
  "defineWhichReports": "Definieer welke rapporten er beschikbaar zijn in de widget:",
  "defaultValues": "Standaardwaarden:",
  "disable": "Uitschakelen",
  "driveTime": "Reistijd",
  "infographics": "Infographics",
  "invalidValueRing": "De waarde moet tussen 0 en 1000 liggen.",
  "invalidValueDTWT": "De waarde moet tussen 0 en 300 liggen.",
  "km": "km",
  "makeDefault": "Standaard maken",
  "miles": "mijl",
  "minutes": "minuten",
  "radius": "Straal",
  "removeDefault": "Standaard verwijderen",
  "reports": "Reports",
  "rings": "Ringen",
  "selectCountryOrRegion": "Selecteer land of regio:",
  "thisEntryIsNotValid": "De ingevoerde waarde is ongeldig.",
  "time": "Tijd",
  "walkTime": "Wandeltijd"
});