// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/MapBuilder","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/promise/all esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when dojo/dom-construct dojo/dom-geometry esri/graphic esri/graphicsUtils esri/dijit/HomeButton ./layers/MapContentBuilder ./legend/LegendBuilder ./MapLoadTracker ./StaticMap ./WebMapsUtil ./Popup ./Projector ./mobile/MobilePanUtil ../../../dataProvider/supportClasses/data/AreaDataUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/ReportPlayer/_devConfig".split(" "),
function(k,l,u,p,h,v,w,r,t,x,y,z,A,B,q,C,n,D,E,F,G){k=k(null,{_mapInfos:null,_mapDivId:0,_mapImageInfos:null,constructor:function(c){l.mixin(this,c);this.reset()},reset:function(){this._mapInfos={};this._mapImageInfos=null},collectAreaMaps:function(c){var b=[];c=c||0;var a=this._mapInfos[c],e;for(e in a){var g=a[e],d=g.node;if(d.parentNode){var f=w.position(d);b.push({areaIndex:c,node:d,x:f.x,y:f.y,position:-1,map:g.map,legend:g.legend,itemId:g.itemId})}}b.sort(function(a,b){return a.x-b.x});b.sort(function(a,
b){return a.y-b.y});b.forEach(function(a,b){a.position=b});return b},collectAllAreasMaps:function(){var c=[],b;for(b in this._mapInfos)c=c.concat(this.collectAreaMaps(b));return c},setFallbackMapImageInfos:function(c){c?(this._mapImageInfos={},c.forEach(function(b){var a=b.areaIndex||0;(this._mapImageInfos[a]=this._mapImageInfos[a]||{})[b.itemId]=b},this)):this._mapImageInfos=null},createMap:function(c,b){b.areaIndex=b.areaIndex||0;q.setLoadedItemsCache(b.reportData.loadedMapPortalItems);return h(this._doCreateMap(c,
b),function(a){return b.waitForLoad?a&&h(A.waitForLoad(a.map),function(){return a}):a})},_doCreateMap:function(c,b){var a=this,e,g;if(b.webMapId)e=q.getItem(b.webMapId);else if(b.calculatorFieldName){var d=E.getAreaDataValue({fieldName:b.calculatorFieldName,fieldData:b.fieldData,featureIndex:b.areaIndex});if(d=d&&d.webMapJson)d=l.mixin({},d),g=[],b.additionalLayerInfos=[],d.operationalLayers=d.operationalLayers.filter(function(a){if(a.isSiteLayer)return g.push(a),!1;if(a.isLocatorLayer)return!1;if(a.isComparisonLayer){var c=
b.stdPolygonsControllers&&b.stdPolygonsControllers.filter(function(b){return b.getCalculatorName()===a.calculatorName});if(c&&c.length){var e=a.featureCollection.layers[0].featureSet,d=c[0].buildGeometryFieldName(e.spatialReference.wkid);e.features.forEach(function(a){a.geometry.spatialReference=l.mixin({},e.spatialReference);a.attributes[d]=JSON.stringify(a.geometry)});c.forEach(function(a){e.features.forEach(function(b){a.saveGeometryInCalculatorData(b.attributes,d)})})}return!1}return!0}),e={item:{type:"Web Map"},
itemData:d}}return h(e,function(e){if(!e||G.emulateErrors.getMapItemError)return(new p).reject(Error("Can't load an item or the item is incorrect."));var d=new p;try{a._prepareFeaturesToShow(b,g),a._createMapFromItem(e,c,b).then(d.resolve,d.reject)}catch(m){d.reject(m),console.log(m)}return d.promise}).otherwise(this._createFallbackStaticMap.bind(this,b,c))},_prepareFeaturesToShow:function(c,b){var a,e={},g=c.areaIndex,d=c.reportData,f=d.analysisAreas;if(b){var h={},m={};b.forEach(function(a){a=a.featureCollection.layers[0];
var b=a.featureSet.features[0],c=b.attributes;b.geometry.spatialReference=a.featureSet.spatialReference;b=new r({geometry:b.geometry,attributes:c,symbol:a.layerDefinition.drawingInfo.renderer.symbol});"esriGeometryPoint"===a.featureSet.geometryType?m[c.STORE_ID]=b:h[c.AREA_ID]=b});f=f.map(function(a){return l.mixin({},a)});f.forEach(function(a){var b=a.feature.attributes;a.feature=h[b.AREA_ID];a.feature&&l.mixin(a.feature.attributes,b);var c=a.location&&a.location.attributes;a.location=m[b.STORE_ID];
a.location&&l.mixin(a.location.attributes,c)})}if(d.isMultiFeature){a=[];var k=d.reverseAnalysisAreasOnMap?f.slice().reverse():f;k.forEach(function(b,c){var f=d.reverseAnalysisAreasOnMap?k.length-c-1:c;e[a.length]=f;a.push(b.feature);c=d.combinedAreasInfo.groups;c&&c.length&&c.some(function(a){return-1!==a.indexes.indexOf(f)})||(b.location&&(e[a.length]=f,a.push(b.location)),b.additionalFeatures&&b.additionalFeatures.forEach(function(b){e[a.length]=f;a.push(b)}))});d.combinedAreasInfo.groups&&d.combinedAreasInfo.groups.forEach(function(b){var c=
f[b.indexes[0]],d=b.location||c&&c.location;d&&(e[a.length]=b.indexes[0],a.push(d),d.locationName=b.locationName||c&&c.locationName);b.additionalFeatures&&b.additionalFeatures.forEach(function(c){e[a.length]=b.indexes[0];a.push(c)})})}else b=f[g],a=[b.feature],b.location&&a.push(b.location),b.additionalFeatures&&(a=a.concat(b.additionalFeatures)),a.forEach(function(a,b){e[b]=g});c.features=a;c.featureIndexToAreaIndexMap=e},_createMapFromItem:function(c,b,a){var e=this,g=F.isMobileDevice();return q.createMap(c,
b,{defaultBasemapId:a.defaultBasemapId,additionalLayerInfos:a.additionalLayerInfos,mapOptions:{extent:a.extent||a.features.length&&t.graphicsExtent(a.features).expand(a.expandFactor||1.5),sliderPosition:!1===a.sliderPosition?"none":a.sliderPosition||"top-right",infoWindow:new C({getPlayerZoomScale:function(){return e.getPlayerZoomScale(b)}},v.create("div")),isMapNavigation:!g}}).then(function(c){var d=c&&c.map;return d?h(e._setInitialExtent(d,a),function(){return h(y.addLayersToMap(d,{features:a.features,
featureIndexToAreaIndexMap:a.featureIndexToAreaIndexMap,analysisAreas:a.reportData.analysisAreas,locatorPointsControllers:a.locatorPointsControllers,stdPolygonsControllers:a.stdPolygonsControllers,thisAreasHighlightController:a.thisAreasHighlightController,geClient:a.geClient,countryID:a.countryID,hierarchy:a.hierarchy,additionalLayerInfos:a.additionalLayerInfos,calculatorFieldName:a.calculatorFieldName,pinSymbolJson:a.pinSymbolJson,areaSymbolJsons:a.areaSymbolJsons,areaSymbolRamp:a.areaSymbolRamp,
attachmentsStore:a.attachmentsStore}),function(){g&&D.setUpMapPan(d,a.onPanContainer);void 0===b.__mapDivId&&(b.__mapDivId=e._mapDivId++);var c={node:b,map:d,itemId:a.webMapId,legend:null};z.createLegend(d,b,a.legendController,{onCreated:function(a){c.legend=a},onDestroyed:function(){delete c.legend}});var f=(new x({map:d})).placeAt(b);f.startup();f.own(d.on("before-unload",function(){f.destroy()}));return(e._mapInfos[a.areaIndex]=e._mapInfos[a.areaIndex]||{})[b.__mapDivId]=c})}):(new p).reject(Error("Can't create a map."))})},
_setInitialExtent:function(c,b){function a(){return u(b.features.map(function(a){return n.needProject(a.geometry,c)?h(n.projectGeometries(a.geometry,c),function(a){return new r(a)}):a})).then(function(a){return t.graphicsExtent(a).expand(b.expandFactor||1.5)})}if(b.features.length)return h(b.extent||a(),function(a){return n.needProject(a,c)?h(n.projectGeometries(a,c),function(a){return c.setExtent(a)}):c.setExtent(a)})},_createFallbackStaticMap:function(c,b){return this._createStaticMap(this._mapImageInfos&&
this._mapImageInfos[c.areaIndex]&&this._mapImageInfos[c.areaIndex][c.webMapId],b,c)},_createStaticMap:function(c,b,a){var e=c&&new B(c,b);return e&&e.load().then(function(){return e.loaded?{node:b,map:e,itemId:a.webMapId,legend:null}:null})},getPlayerZoomScale:function(c){}});k.EXPAND_FACTOR=1.5;return k});