// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/CustomReportsManager","dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when ./PortalManager ./ReportTemplateData ./StandardGraphicReportTemplates esri/dijit/geoenrichment/utils/CacheUtil esri/dijit/geoenrichment/utils/PortalUtil esri/dijit/geoenrichment/utils/PortalQueryUtil esri/dijit/geoenrichment/utils/UrlUtil ../../config ../../countryConfig".split(" "),function(k,q,f,l,r,t,m,u,v,g,n,w){var p=
{TEMPLATE_TYPE:"Report Template",PLAYER_STANDARD_INFOGRAPHIC_TYPEKEYWORD:"esriReportPlayerStandardInfographic",GALLERY_INFOGRAPHIC_TYPEKEYWORD:"esriWebGalleryInfographicReport",MOBILE_INFOGRAPHIC_TYPEKEYWORD:"esriMobileFactsInfographicReport",GALLERY_INFOGRAPHIC_USER:"esri_reports",resetCache:function(){m.set("CustomReportsManager",{})},_getCache:function(){return m.get("CustomReportsManager")},getCustomReports:function(a){var d=this,c=g.getPortalUrl(a.portalUrl);return f(l.getPortalInfo(c),function(e){var b=
e.user.username,b={q:v.combineQueryString({type:"Report Template",typeKeywords:a.typeKeywords,owner:!a.publicOnly&&b}),sortField:"modified",sortOrder:"desc"};return u.queryCommon(g.combine(c,"sharing/rest/search"),b).then(function(b){b=b.map(function(b){return d.prepareCustomReportFromItem(b,e.portal.url,a)});return d._getCountryReports(b,a.countryID)})})},_getCountryReports:function(a,d){return a&&("*"===d?a:a.filter(function(a){return!a.countries||a.countries.split(",").some(function(a){return d===
a.trim()})}))},prepareCustomReportFromItem:function(a,d,c){function e(a){return"string"===typeof a?"true"===a:!!a}var b=k.mixin({},a.properties||a.details);b.isGraphicReport=e(b.isGraphicReport);b.isMultiFeature=e(b.isMultiFeature);b.reportID=a.id;d={title:a.title,templateData:d&&new r(a,d),modified:a.modified instanceof Date?a.modified.getTime():a.modified};c&&c.attachItemProperty&&(d[c.attachItemProperty]=a);k.mixin(d,b);return d},getCustomReportByID:function(a){var d=this,c=this._getCache()[a.reportID];
if(c)return c;c=g.getPortalUrl(a.portalUrl);return this._getCache()[a.reportID]=f(l.getPortalInfo(c),function(c){return c.user.getItem(a.reportID).then(function(b){return b&&d.prepareCustomReportFromItem(b,c.portal.url,a)})}).otherwise(function(c){delete d._getCache()[a.reportID];return a.ignoreError?null:(new q).reject(c)})},tryFindReportIdByAlias:function(a){var d=this,c=t.aliasToID(a.countryID,a.reportID);if(!c)return null;var e=g.getPortalUrl(a.portalUrl);return f(this.getCustomReportByID({reportID:c,
portalUrl:e,ignoreError:!0,attachItemProperty:a.attachItemProperty}),function(b){return b?b&&(a.returnObject?b:b.reportID):f(d.getCustomReports({portalUrl:e,countryID:a.countryID,typeKeywords:"esriReportPlayerStandardInfographic",publicOnly:!0,attachItemProperty:a.attachItemProperty}),function(b){function c(a){a=a.split(".");return Number((Number(a[0])+Number(a[1])/100).toFixed(2))}var d=c(n.jsapiVersion),e,f,g=-Infinity,k=Infinity;b.forEach(function(b){if(b.playerAlias===a.reportID){var h=c(b.jsapiVersion);
d>=h&&h>g&&(g=h,e=b);d<h&&h<k&&(k=h,f=b)}});b=e||f;a.strictVersionCheck&&b&&b.jsapiVersion!==n.jsapiVersion&&(b=null);return b&&(a.returnObject?b:b.reportID)})})},itemUpdated:function(a){delete this._getCache()[a]},getFakeCustomReportByContext:function(a){return{title:"Generic template",type:"esriReportTemplateStandard",coverage:a.countryID,countries:a.countryID,hierarchy:a.hierarchy||w.getHierarchyID(),isGraphicReport:!0,isMultiFeature:!1,reportID:null}}};p.resetCache();return p});