// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/GEUtil","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when esri/dijit/geoenrichment/promise/all dojox/uuid/generateRandomUuid esri/kernel esri/request esri/urlUtils esri/dijit/geoenrichment/utils/CacheUtil esri/dijit/geoenrichment/utils/requests/FileContent esri/dijit/geoenrichment/utils/requests/UniversalClient esri/dijit/geoenrichment/utils/UrlUtil ./stdGeographies/StdGeographiesModel".split(" "),
function(x,q,r,n,y,z,v,g,A,k,B,t,C,D){function E(a){return p?p:(a=a&&v.id.findCredential(a)||v.id.credentials[0])&&a.token}function f(a,b){var d=A.urlToObject(a);b=q.mixin({f:"json",token:E(a),langCode:dojo.locale},d.query||{},b);for(var l in b)a=b[l],a instanceof B||a&&"object"===typeof a&&(b[l]=JSON.stringify("function"===typeof a.toJson?a.toJson():a));return{url:d.path,taskParams:b}}function e(a){h||(h=new w(m));return!a||h.initialized?h:h.initialize()}var w=x(null,{url:null,_geInfo:null,_capabilities:null,
_supportedOperations:null,constructor:function(a){this._capabilities={};this._supportedOperations={};this.url=a},_initDfd:null,initialized:!1,initialize:function(){var a=this;if(this._initDfd)return this._initDfd.promise;this._initDfd=new r;t.requestPublicFirst(f(this.url).url+"/Geoenrichment",{content:{f:"json"},handleAs:"json"},{retryOnAnyError:!0}).then(function(b){a.initWithJson(b)});return this._initDfd.promise},initWithJson:function(a){this._geInfo=a;this._capabilities={};this._supportedOperations=
{};a.capabilities&&a.capabilities.forEach(function(a){this._capabilities[a.toLowerCase()]=!0},this);a.supportedOperations&&a.supportedOperations.forEach(function(a){this._supportedOperations[a.toLowerCase()]=!0},this);this._initDfd=this._initDfd||new r;this._initDfd.resolve();this.initialized=!0},hasCapability:function(a){return!!this._capabilities[a.toLowerCase()]},addCapability:function(a){this._capabilities[a.toLowerCase()]=!0},supportsOperation:function(a){return!!this._supportedOperations[a.toLowerCase()]},
enrich:function(a){a=f(this.url,a);a.taskParams.AddDerivativeVariables="all";return g({url:a.url+"/Geoenrichment/Enrich",content:a.taskParams,handleAs:"json"}).then(function(a){return a.results[0].value.FeatureSet||[]})},stdGeographyQuery:function(a){a=f(this.url,a);return g({url:a.url+"/StandardGeographyQuery/execute",content:a.taskParams,handleAs:"json"}).then(function(a){return a.results[0].value.features||[]})},getDataCollections:function(a,b,d){d=f(this.url,d);return g({url:d.url+"/Geoenrichment/DataCollections/"+
a+(b?"/"+b:""),content:d.taskParams,handleAs:"json"}).then(function(a){return a.DataCollections})},getCountries:function(){var a=f(this.url);return g({url:a.url+"/Geoenrichment/Countries",content:a.taskParams,handleAs:"json"}).then(function(a){return a.countries})},getCountryInfo:function(a){var b=this,d=k.get("GEUtil.countries");if(!d[a]){var c=f(this.url);d[a]=g({url:c.url+"/Geoenrichment/Countries/"+a,content:c.taskParams,handleAs:"json"}).then(function(d){var c=d.countries[0],l={};return y(c.hierarchies.map(function(d){return n(b._getStdGeographyModel(a,
d.ID),function(a){l[d.ID]=a})})).then(function(){return{country:c,geographiesModels:l}})})}return d[a]},_getStdGeographyModel:function(a,b){var d=k.get("GEUtil.stdModels"),c=a+b;if(!d[c]){var e=f(this.url);d[c]=g({url:e.url+"/Geoenrichment/StandardGeographyLevels/"+a+"/"+b,content:e.taskParams,handleAs:"json"}).then(function(d){return new D({countryID:a,hierarchyID:b,levels:d.geographyLevels[0].hierarchies[0].levels})})}return d[c]},formatReport:function(a){a=f(this.url,a);return t.request({url:a.url,
urlSuffix:"Geoenrichment/FormatReport"},{handleAs:"bin",content:a.taskParams}).then(function(a){return a&&a.data&&"text/plain"===a.data.type?null:a})},getReports:function(a){var b=f(this.url);return g({url:b.url+"/Geoenrichment/reports/"+a,content:b.taskParams,handleAs:"json"}).then(function(a){return a.reports})},createReport:function(a){var b=f(this.url,a),d=z();k.get("GEUtil.tasks")[d]={taskName:"createReport",taskParams:q.clone(a)};return t.request({url:b.url,urlSuffix:"Geoenrichment/createReport"},
{handleAs:"xml"===a.format?"text":"bin",content:b.taskParams}).then(function(a){return{taskID:d,result:a}})},consumeCredits:function(a){if(a=k.get("GEUtil.tasks")[a])return a=q.clone(a),delete a.taskParams.forStorage,this[a.taskName](a.taskParams)},getLayerInfos:function(a){var b=k.get("GEUtil.dataLayers");b[a]||(b[a]=this._getLayerInfos(a));return b[a]},_getLayerInfos:function(a){var b=f(this.url);return g({url:b.url+"/Geoenrichment/DataLayers/"+a,content:b.taskParams,handleAs:"json"}).then(function(a){return a&&
a.layers||[]}).otherwise(function(a){console.log(a);return[]})},getLayerInfo:function(a,b){var d=k.get("GEUtil.dataLayers"),c=a+"_"+b;d[c]||(d[c]=this._getLayerInfo(a,b));return d[c]},_getLayerInfo:function(a,b){var c=f(this.url);return g({url:c.url+"/Geoenrichment/DataLayers/"+a+"/"+b,content:c.taskParams,handleAs:"json"}).then(function(a){return a&&a.layer}).otherwise(function(a){console.log(a);return null})}}),c={},m,p,u=new r;c.setGeoenrichmentUrl=function(a,b){(m=a||m)&&C.registerCORS(m);p=b||
p;!u.promise.isFulfilled()&&u.resolve()};c.canMakeRequests=function(){return!!m};c.getInitPromise=function(){return u.promise};c.GEClient=w;var h;c.getClient=function(){return e()};c.initialize=function(){return n(e(!0))};c.initWithJson=function(a,b){c.setGeoenrichmentUrl(a);e().initWithJson(b)};c.enrich=function(a){return e().enrich(a)};c.stdGeographyQuery=function(a){return e().stdGeographyQuery(a)};c.getDataCollections=function(a,b,c){return e().getDataCollections(a,b,c)};c.formatReport=function(a){return e().formatReport(a)};
c.createReport=function(a){return e().createReport(a)};c.consumeCredits=function(a){return e().consumeCredits(a)};c.getLayerInfos=function(a){return e().getLayerInfos(a)};c.hasCapability=function(a){return n(e(!0),function(){return h&&h.hasCapability(a)})};c.addCapability=function(a){return e().addCapability(a)};c.supportsOperation=function(a){return n(e(!0),function(){return h&&h.supportsOperation(a)})};c.getCountryInfo=function(a){return e().getCountryInfo(a)};return c});