// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/InfographicContainer.html":'\x3cdiv class\x3d"esriGEReportPlayer_infographicContainer esriGEAbsoluteStretched"\x3e\r\n    \x3cdiv class\x3d"infographicContainer_viewDiv" data-dojo-attach-point\x3d"viewDiv"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicContainer","require dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicTypes esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/WaitingUtil dojo/text!../templates/InfographicContainer.html".split(" "),function(l,
m,h,e,c,n,p,d,f,q,k,r){return m([n,p],{isInfographic:!0,templateString:r,viewModel:null,theme:null,parentWidget:null,currentFeatureIndex:null,getPreviewValueFunction:null,adjustElementsWhenResized:!1,_pendingResizeFlag:!1,_pendingUpdateFlag:!1,postCreate:function(){this.inherited(arguments);this._initDfd=new e},_initDfd:null,_currentInfographic:null,_isBeingUpdated:!1,getInnerInfographic:function(){return this._currentInfographic},getContentInitPromise:function(){return this._initDfd&&this._initDfd.promise},
getRenderPromise:function(){return c(this._initDfd&&this._initDfd.promise).then(function(){return this._currentInfographic&&this._currentInfographic.getRenderPromise()}.bind(this))},_getTypeToClassPathMap:function(){var a={};a[d.STATIC]="./simpleInfographic/SimpleInfographicWithDataDrilling";a[d.ATTACHMENTS]="./AttachmentsInfographic";a[d.AREA_DETAILS]="./areaDetails/AreaDetailsInfographic";a[d.LOCATOR_TABLE]="./locator/LocatorTableInfographic";a[d.COMPARISON_TABLE]="./comparison/ComparisonTableInfographic";
a.dynamic="./dynamic/DynamicInfographic";return a},_getRelativeRequire:function(){return l},_lastAppliedJson:null,updateInfographic:function(a){var b=this;if(this.viewDiv&&a&&d.isSupported(a.type)&&!this._isBeingUpdated){a.style=a.style||{};this._lastAppliedJson=a;this._type=a.type;if(this._currentInfographic)return this._currentInfographic.updateInfographic(a);this._initDfd=this._initDfd||new e;this._isBeingUpdated=!0;var c=this._getTypeToClassPathMap()[d.isDynamic(a.type)?"dynamic":a.type],g=new e;
this._getRelativeRequire()([c],function(a){g.resolve(a)});k.showProgressPromise(this.domNode,g.promise);return g.promise.then(function(c){b._createInfographicForClass(a,c)}).then(function(){b._isBeingUpdated=!1;f.isNodeInLayout(b.domNode)?b._currentInfographic.updateInfographic(a):b._pendingUpdateFlag=!0;b._initDfd.resolve();b._initDfd=null;return b.getRenderPromise()})}},_createInfographicForClass:function(a,b){var c=this,d=h.mixin({viewModel:this.viewModel,theme:this.theme,parentWidget:this,currentFeatureIndex:this.currentFeatureIndex,
getPreviewValueFunction:this.getPreviewValueFunction,width:this.width,height:this.height,adjustElementsWhenResized:this.adjustElementsWhenResized,onShowWaiting:function(a){return k.showProgressPromise(c.domNode,a)}},this._prepareCreationParameters(a),d);this._currentInfographic=new b(d);this._currentInfographic.placeAt(this.viewDiv);return this._currentInfographic},_prepareCreationParameters:function(a){return null},_type:null,getType:function(){return this._type},width:null,height:null,resize:function(a,
b){void 0!==a&&(this.width=a,this.height=b);c(this._initDfd&&this._initDfd.promise,function(){f.isNodeInLayout(this.domNode)?this._currentInfographic&&this._currentInfographic.resize(this.width,this.height):this._pendingResizeFlag=!0}.bind(this))},getPreferredHeight:function(){return this._currentInfographic&&this._currentInfographic.getPreferredHeight&&this._currentInfographic.getPreferredHeight()},collapseContent:function(){this._currentInfographic&&this._currentInfographic.collapseContent&&this._currentInfographic.collapseContent()},
toJson:function(){return this._currentInfographic?this._currentInfographic.toJson():this._lastAppliedJson&&h.clone(this._lastAppliedJson)},getVisualState:function(){return this._currentInfographic&&this._currentInfographic.getVisualState&&this._currentInfographic.getVisualState()},setVisualState:function(a){return this._currentInfographic&&this._currentInfographic.setVisualState&&this._currentInfographic.setVisualState(a)},notifyShown:function(){c(this._initDfd&&this._initDfd.promise,function(){f.isNodeInLayout(this.domNode)&&
(this._pendingResizeFlag&&this.resize(),this._pendingResizeFlag=!1,this._pendingUpdateFlag&&this._currentInfographic.updateInfographic(this._lastAppliedJson),this._pendingUpdateFlag=!1,c(this.getRenderPromise(),function(){this._currentInfographic&&this._currentInfographic.notifyShown&&this._currentInfographic.notifyShown()}.bind(this)))}.bind(this))},_panelScale:null,notifyPanelScaleChanged:function(a){this._panelScale=a;c(this._initDfd&&this._initDfd.promise,function(){this._currentInfographic&&
this._currentInfographic.notifyPanelScaleChanged&&this._currentInfographic.notifyPanelScaleChanged(this._panelScale)}.bind(this))},isMouseOver:function(){return q.isMouseOver(this.domNode)||this._currentInfographic&&this._currentInfographic.isMouseOver&&this._currentInfographic.isMouseOver()},destroy:function(){this._currentInfographic&&this._currentInfographic.destroy();this.inherited(arguments)}})});