// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/FieldParser","esri/dijit/geoenrichment/utils/JsonXmlConverter ../../../supportClasses/templateJsonUtils/fieldInfo/RichTextJsonUtil ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoFormatUtil ../../ConversionUtil ../../ShapeConverter ../../../annotations/shape/ShapeJsonUtil ./_FieldInfoBuilder ./ImageParser ./MapParser ./AlignParser ../../../../_devConfig".split(" "),
function(h,A,k,B,l,t,C,p,D,u,E,v){function q(a){a=a.attributes||{};B.processFieldInfoTagAttributes(a);return a}function w(a,c,b){if(c=h.queryTopJson(c,"section")[0])a.dataDrillingPanelInfo={sectionJson:b.parsers.getParser("section").parseSection(c,b)}}function x(a,c,b){var d=c.attributes||{};a.tooltipInfo={value:!!d.value,alias:!!d.alias,expression:!!d.expression,conditional:!!d.conditional,fieldInfo:null,style:l.ptToPxObj(l.parseStyleString(d.style))};c=h.queryTopJson(c,"textContent")[0];a.tooltipInfo.fieldInfo=
c&&b.parsers.getParser("field").parseRichTextTag(c,b)}function y(a){return h.queryJson(a,/^d$|^text$|^reportName$|^reportTitle2/)}var m={},r={parseImageTrigger:function(a,c){var b=p.getCalculatorOrScriptFieldInfo(a.attributes.field,c);if(!b)return console.log("Parse template error \x3d\x3e can't build fieldInfo for field "+a.attributes.field),console.log(a),null;var d={fieldInfo:b,cases:[]},f=this;a.tags.forEach(function(a){var b="case"===a.name?a.attributes.key:"default";a=a.tags[0];var e=c.processFileName(a.attributes.value);
d.cases.push({compareInfos:f._getCompareInfosFromTriggerKey(b),setters:[{property:a.attributes.property,value:e}]});e&&c.putImageData(e)});return d},parseFieldTrigger:function(a,c,b){c.triggerJson={fieldInfo:b&&p.getCalculatorOrScriptFieldInfo(a.attributes.field,b),cases:[]};var d=this;a.tags.forEach(function(a){var b={compareInfos:d._getCompareInfosFromTriggerKey("case"===a.name?a.attributes.key:"default"),setters:[]};c.triggerJson.cases.push(b);a.tags.forEach(function(a){b.setters.push({property:a.attributes.property,
value:a.attributes.value})})})},_getCompareInfosFromTriggerKey:function(a){return a.split(l.KEY_INTERVAL_SEPARATOR).map(function(a){var b=l.ONE_FIELD_KEY_TEST.test(a)?a.replace(l.KEY_OPERATOR_RE,""):a;a=a.substr(0,a.length-b.length)||"\x3d";return{value:b,operator:a}})}},F={getFieldInfo:function(a,c,b){return(a=b.parsers.getParser("chart").portalToEditor(a,c,b))&&k.createFieldInfoFromChart(a)}},G={getFieldInfo:function(a,c,b){return(a=b.parsers.getParser("infographic").portalToEditor(a,c,b))&&k.createFieldInfoFromInfographic(a)}},
H={getFieldInfo:function(a,c,b){c=D.getElement(a,b);var d,f=h.queryTopJson(a,"trigger")[0];f&&(d=r.parseImageTrigger(f,b))&&((f=(f=h.queryTopJson(a,"dataDrillingPanels")[0])&&h.queryTopJson(f,"dataDrillingPanel")[0])&&w(d.fieldInfo,f,b),(a=h.queryTopJson(a,"tooltip")[0])&&x(d.fieldInfo,a,b));return k.createFieldInfoFromImage(c,d)}},I={getFieldInfo:function(a,c,b){a=u.getElement(a,b);return k.createFieldInfoFromMap(a)}},J={getFieldInfo:function(a,c,b){c=t.svgJsonToShapeObject(a);var d=t.getStylesFromSvgJson(a);
c=C.createShapeJsonFromShapeObj(c,d);a=a.attributes;c.style.angle=Number(a.angle)||0;E.parseAlign(a,c.style);2>b.revisionVersion&&(b=Math.max(0<c.style.borderAlpha&&c.style.borderWidth||0,0<c.backgroundStyle.borderAlpha&&c.backgroundStyle.borderWidth||0),0<b&&(a=c.viewBox,a.xmin=a.xmin||0,a.ymin=a.ymin||0,a.xmin-=b/4,a.ymin-=b/4,a.width+=b/2,a.height+=b/2));return k.createFieldInfoFromShape(c)}},K={getFieldInfo:function(a,c,b){a=b.parsers.getParser("section").parseSection(a,b);return k.createFieldInfoFromSection(a)}},
n={getFieldInfo:function(a,c,b,d,f,h,g){a=q(a);g=g||a.f;if(b.templateJson.metadata.mapImageInfosHash[g])return c=u.parseMapImageDField(g,b),k.createFieldInfoFromMap(c);var e=k.createFieldInfoFromSpecialFieldName(g,a.m);if(!e){var z;2===c.tags.length&&c.tags[1].text&&(z=c.tags[1].text);e=p.getCalculatorOrScriptFieldInfo(g,b,{format:a.m,additionalText:z,summaryType:a.summary})}e&&d&&(r.parseFieldTrigger(d,e,b),e.triggerJson&&!e.triggerJson.fieldInfo&&(e.triggerJson.fieldInfo=null,console.log("Parse template error \x3d\x3e can't build fieldInfo for field "+
d.attributes.field),console.log(d)));e&&f&&w(e,f,b);e&&h&&x(e,h,b);return e}};m.parseField=function(a,c,b,d,f,h){var g;if(v.emulateErrors.layoutParseError)throw v.emulateErrors.layoutParseError--,Error("Error test: something crashed during the parsing of the layout!");if(a){if("chart"===a.name)return F.getFieldInfo(a,c,b);if("infographic"===a.name)return G.getFieldInfo(a,c,b)||!1;if("img"===a.name&&a.attributes)return H.getFieldInfo(a,c,b);if("mapImage"===a.name&&a.attributes)return I.getFieldInfo(a,
c,b);if("svg"===a.name)return J.getFieldInfo(a,c,b);if("section"===a.name)return K.getFieldInfo(a,c,b);if("d"===a.name)g=n.getFieldInfo(a,c,b,d,f,h);else if("a"===a.name&&a.tags&&"d"===a.tags[0].name){var e=a.tags[0];(g=n.getFieldInfo(e,c,b,d,f,h))&&a.attributes&&a.attributes.hreff&&(g.linkFieldInfo=n.getFieldInfo(e,c,b,d,f,h,a.attributes.hreff))}else g="text"===a.name?k.createFieldInfoFromSpecialFieldName(q(a).name):k.createFieldInfoFromSpecialFieldName(a.name,q(a).m)}if(!g){a=y(c);if(1===a.length&&
a[0].attributes&&"TrialUrlText"===a[0].attributes.name)return k.createFieldInfoFromSpecialFieldName(a[0].attributes.name);g=m.parseRichTextTag(c,b)}return g};m.parseRichTextTag=function(a,c){var b,d=/^img$|^script/;h.queryJson(a,d).length&&(a.innerHTML=null,a.tags=a.tags.filter(function(a){return!d.test(a.name)}));var f=y(a);if(f.length){var l=[],g=!0;f.some(function(b){var d=b.attributes?b.attributes.name:b.name;b="d"===b.name?n.getFieldInfo(b,a,c):d&&k.createFieldInfoFromSpecialFieldName(d);if(!b)return g=
!1,!0;l.push(b)});g&&(b=A.createFieldInfoFromRichText(h.getInnerHTML(a),l))}return b};m.parseFieldTrigger=function(a,c,b){c=c||{};r.parseFieldTrigger(a,c,b);return c.triggerJson};return m});