// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/_ServerSerializationSupport","dojo/_base/declare esri/dijit/geoenrichment/when esri/dijit/geoenrichment/utils/ImageUtil ./supportClasses/ReportDataProcessor ./supportClasses/tasks/parsers/DataXMLParser ./supportClasses/areas/AnalysisAreaUtil ./supportClasses/areas/AnalysisAreaJsonUtil ./supportClasses/areas/AreasPreprocessor ./supportClasses/GEUtil ../core/supportClasses/ReportTemplateTypes ../core/conversion/PortalToEditorConverter ../core/supportClasses/map/WebMapJsonUtil ../core/supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ./supportClasses/attachments/AttachmentsStoreSerializer ../core/supportClasses/templateJsonUtils/TemplateJsonSerializer ../core/conversion/portalToEditorUtils/variables/PlayerVariableProvider ../core/conversion/portalToEditorUtils/metadata/MetadataFromDataBuilder ../countryConfig".split(" "),
function(l,h,q,y,z,r,t,A,m,B,C,D,E,F,G,H,I,J){return l(null,{reportDataToServerData:function(d){return null},reportDataFromServerData:function(d,u){function l(c){e.some(function(c){return"metadata.xml"===c.name})||e.push({name:"metadata.xml",data:I.recoverMetadataFromAreaData(k.areaData,c)})}function K(c){d.sites=[];var e={},f=1;k.areaData.forEach(function(a){a=a.headers&&a.headers.data||{};var b=a.SITE_NAME||a.STORE_NAME,c=a.STORE_ID||"unclassified."+f++;"number"!==typeof e[c]&&(e[c]=d.sites.length,
d.sites.push({locationName:b,name:null,shortName:null,description:null,address:a.STORE_ADDR,latitude:a.STORE_LAT,longitude:a.STORE_LONG,areas:[]}));d.sites[e[c]].areas.push({locationName:b,name:a.AREA_DESC?b+" ("+a.AREA_DESC+")":b,shortName:a.AREA_DESC,description:a.AREA_DESC2,address:a.STORE_ADDR,latitude:a.STORE_LAT,longitude:a.STORE_LONG,feature:{attributes:{STORE_ID:a.STORE_ID,AREA_ID:a.AREA_ID}}})});d.sites.forEach(function(a){var c=!1;a.shortName=a.areas.map(function(a){return c=!!a.shortName,
a.shortName}).join(", ");c&&(a.name=a.locationName+" ("+a.shortName+")");var g=a.areas.map(function(a){return a.description});a.description=1<g.length?g[0]===g[1]?g[0]:g.join(", "):g[0]||""});k.reportInfo.sites&&k.reportInfo.sites.forEach(function(a,b){if(b=d.sites[b])b.attributes=a.attributes,b.notes=a.notes,b.images=a.images,b.images&&b.images.forEach(function(a){function b(a){return(a=c[a])&&q.base64DataToDataURL(a,"image/png")}a.url=b(a.url);a.thumbnail=b(a.thumbnail)})})}J.reset();var e=d.reportItem.resources,
v;if(!Array.isArray(e)){var w=e,e=[],n;for(n in w)e.push({name:n,data:w[n]})}e.forEach(function(c){"theme.css"===c.name&&(c.name="theme.css.txt")});var p=e.filter(function(c){return"report.xml"===c.name})[0],L=e.filter(function(c){return"data.xml"===c.name})[0],k;(function(){var c=/.*\.(png|jpg|jpeg)$/i,d=/(.*\.(json)$)|(^maps\/.*\.(png)$)/i,f={},a={};e.forEach(function(b){c.test(b.name)&&(f[b.name]=b.data,"logo.png"===b.name&&(v=q.base64DataToDataURL(b.data,"image/png")));d.test(b.name)&&(-1!==b.data.indexOf("operationalLayers")?
a[b.name]=D.processWebMapJson(b.name,b.data):a[b.name]=b.data)});var b={},g=p.data.match(/<section[^<>]*query=("|').+?("|').*?>/g);g&&g.forEach(function(a){a=a.replace(/.*?query=("|')/,"");a=a.replace(/("|').*/,"");b[a]=1});var h={};k=z.parse(L.data,function(b,c,d){return(b=a[c])?h[d]=b:f[c]||c});l({map:h,locator:b});K(f)})();var x=new H;return h(function(c){var d=p.data.indexOf("\x3csection"),f={isGraphicReport:p.data.indexOf("\x3ctable")<d,isMultiFeature:!1,defaultComparisonZoom:null,type:B.STANDARD,
portalJson:{files:e}};return h(C.provideEditorJson(f,{variableProvider:c}),function(){f.templateJson=G.deserialize(f.templateJson);f.isMultiFeature=E.hasMultiFeatureSections(f.templateJson);delete f.portalJson;return f})}(x),function(c){r.parseSites(d);var e=t.areasFromJson(d.analysisAreas),f=d.combinedAreasInfo&&t.combinedAreasInfoFromJson(d.combinedAreasInfo)||{},a=d.attachmentsProvider&&F.getAttachmentsStoreFromJson(d.attachmentsProvider),b={isMultiFeature:c.isMultiFeature&&1<e.length,reportTitle:null,
templateJson:c.templateJson,reportObject:c,fieldData:{specialTradeAreaCalculatorName:null,runReportTaskIDs:null,metadata:{},areaData:[],errors:[],reportInfo:null},analysisAreas:e,combinedAreasInfo:f,reverseAnalysisAreasOnMap:!0,attachmentsStore:a,templateVariableProvider:x,customLogo:v,config:{}};r.populateCombinedAreasInfo(b.combinedAreasInfo,b.analysisAreas);A.provideAreasIndexes(b);m.setGeoenrichmentUrl(null);u&&u.forEach(function(a){switch(a){case "Maps":m.addCapability("FormatInfographicsMaps");
break;case "ImageUrls":m.addCapability("FormatInfographicsImageUrls")}});return h(y.applyRunReportAndGetDataResults(k,b)).then(function(){return b})})}})});