// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/DynamicInfographic.html":'\x3cdiv data-dojo-attach-point\x3d"viewDiv" class\x3d"esriGE_dynamicInfographic"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"noDataPlaceHolder" class\x3d"esriGENoDataPlaceHolder"\x3e\r\n        \x3cdiv class\x3d"esriGENoDataPlaceHolderLabel"\x3e${nls.noInfographicData}\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"infographicDiv"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"errorDiv" class\x3d"esriGEReportPlayerPanelErrorMessage"\x3e${nls.dynamicInfographicError}\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/dynamic/DynamicInfographic","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when dojo/dom-style dojo/query dojo/on dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/ReportPlayer/config esri/dijit/geoenrichment/infographicUtils/theme ./_Infographic ../InfographicTypes esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/ge/LocalGEInfographic esri/dijit/geoenrichment/utils/DelayUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/ObjectUtil ../utils/InfographicJsonUtil ../extentions/BaseSelectComparisonExt dojo/text!../../templates/DynamicInfographic.html dojo/i18n!esri/nls/jsapi ../../../_devConfig".split(" "),
function(l,r,h,d,n,m,v,w,x,y,t,c,z,A,k,B,C,u,p,D,E,q,F){q=q.geoenrichment.dijit.ReportPlayer.Infographics;var g={};g[c.ONE_VAR]=230;g[c.AGE_PYRAMID]=0;g[c.RELATED_VARS]=320;g[c.TAPESTRY]=300;g[c.PRIZM5]=300;l=l([v,w],{templateString:E,nls:q,viewModel:null,theme:null,currentFeatureIndex:null,_infographic:null,_stdPolygonsController:null,_thisAreasHighlightController:null,_initPromise:null,buildRendering:function(){D.init();this.inherited(arguments)},postCreate:function(){this.inherited(arguments);
this._showError(!1);this._showEmptyView(!1)},_currentInfographicJson:null,getRenderPromise:function(){return this._initPromise},updateInfographic:function(a){if(this.viewDiv)return this._destroyCurrentInfographic(),this._currentInfographicJson=a,this.viewModel.dynamicReportInfo&&this._currentInfographicJson.calcData&&c.supportsComparison(this._currentInfographicJson.type)&&(this._stdPolygonsController=this.viewModel.getStdPolygonsController(this._currentInfographicJson.calcData.calculatorName,this.currentFeatureIndex),
this._currentInfographicJson.type===c.ONE_VAR&&(this._thisAreasHighlightController=this.viewModel.getThisAreasHighlightController())),this._enrichInfographicJsonWithProps(a),this.domNode.style.opacity="0.001",this._initPromise=h(this._createInfographicWidgetFromJson(a),function(){this.domNode&&(this._applyTheme(a),this.domNode.style.opacity="")}.bind(this))},_enrichInfographicJsonWithProps:function(a){p.setLevels(a,a.levels)},_createInfographicWidgetFromJson:function(a){var b=this,f=this.viewModel.getInfographicDefaultStyles(this.theme);
y.set(this.viewDiv,f&&f.agePyramid&&f.agePyramid.theme||"light");if(this.viewModel.dynamicReportInfo){this.viewModel.dynamicReportInfo.isFixedDataMode||this.viewModel.dynamicReportInfo.geClient.hasCapability("ComparisonLevelsInCalculators")||(a.calcData=null);this._infographic=(new t({documentStyleProvider:this.viewModel.getDocumentDefaultStyles(this.theme),infographicStyleProvider:f,chartStyleProvider:this.viewModel.getChartDefaultStyles(this.theme),widgetParams:this._getWidgetCreationParams(a),
returnGeometry:!1,autoTitle:!1,subtitle:!1,levels:p.getSubLevels(a),highestLevel:p.getHighestLevel(a),onExpandedStateChanged:function(){b._doResize()},onSelectedFeatureChanged:function(){b._syncWithShownFeatures()}})).placeAt(this.infographicDiv);var f=a.title,d=a.variables||a.calcData.variables,e=new z(a,this.viewModel.dynamicReportInfo.fieldData.areaData,this.currentFeatureIndex);this._infographic.setGeoenrichment(e);this._infographic.set("expanded",a.type===c.TAPESTRY||1<e.getData().features.length);
this._infographic.set("countryID",this.viewModel.dynamicReportInfo.countryID);this._infographic.set("type",a.type);this._infographic.set("variables",d);this._infographic.set("title",f);this._infographic.startup();a.title=a.title||f;return h(this._infographic.getRenderPromise(),function(){return b._doResize().then(function(){b._syncWithShownFeatures()})})}try{return this._createDummyInfographic(a)}catch(G){console.log(G),this._showError(!0)}},_getWidgetCreationParams:function(a){var b={};switch(a.type){case c.AGE_PYRAMID:b.showVerticalAxis=
a.showVerticalAxis;break;case c.TAPESTRY:case c.PRIZM5:b.titleStyle=a.style.titleStyle,b.backgroundColor=a.style.backgroundColor,b.tableBackgroundColor=a.style.tableBackgroundColor,b.tableBorderColor=a.style.tableBorderColor,b.textStyle=a.style.textStyle,b.subtextStyle=a.style.subtextStyle,b.hyperlinkTextStyle=a.style.hyperlinkTextStyle,b.detailsValueBorderColor=a.style.detailsValueBorderColor}return b},_createDummyInfographic:function(a){},_syncWithShownFeatures:function(){if(this._stdPolygonsController&&
this._infographic&&this._infographic._widget){this._stdPolygonsController.setAttributeFields(this._infographic.dataProvider.getAttributeFields());var a=this._infographic.dataProvider.getAllGeographyAttributes({ignoreFilters:!0}),b;if(this._currentInfographicJson.type===c.ONE_VAR)b=this._infographic.dataProvider.getAllGeographyAttributes();else{b=[];var f=this._infographic._widget.select&&this._infographic._widget.select.getSelectedAttributes();f&&b.push(f)}this._stdPolygonsController.setShownFeatureAttributes(b);
this._stdPolygonsController.setAllFeatureAttributes(a);this._currentInfographicJson.type===c.ONE_VAR&&(this._registerStdPolygonsHighlight(a),this._registerThisAreaHighlight())}},_registerStdPolygonsHighlight:function(a){var b=this;this._stdPolygonsController.registerInfographic({highlightInfographicForAttributes:function(a){b._isCreated()&&(a=b._infographic._widget.setTableRowHighlighted(a))&&(b.viewDiv.scrollTop=a.offsetTop+200-b.viewDiv.clientHeight)}}).then(function(){if(b._isCreated()){var f;
m(b._infographic._widget.table,"mouseover, mousemove",function(){var c=b._infographic._widget.getOverRow();if(c&&c!==f){var e=(f=c)&&c.cells[0].innerHTML,d;e&&a.some(function(a){if(a.StdGeographyName===e)return d=a,!0});d&&(b._stdPolygonsController.highlightGraphicForAttributes(d),b._infographic._widget.setTableRowHighlighted(d))}});m(b._infographic._widget.table,"mouseout",function(){b._stdPolygonsController.highlightGraphicForAttributes(null);b._infographic._widget.setTableRowHighlighted(null);
f=null})}})},_registerThisAreaHighlight:function(){var a=this;this._thisAreasHighlightController.registerTable({highlightTableForAreaIndex:function(b){if(a._isCreated())if(a.currentFeatureIndex===b){if(b=a._infographic._widget.setThisAreaTableRowHighlighted())a.viewDiv.scrollTop=b.offsetTop+200-a.viewDiv.clientHeight}else a._infographic._widget.setTableRowHighlighted(null)}}).then(function(){if(a._isCreated()){var b;m(a._infographic._widget.table,"mouseover, mousemove",function(){var c=a._infographic._widget.getOverRow();
c&&c!==b&&(b=c,a._infographic._widget.isThisAreaRow(b)&&(a._thisAreasHighlightController.highlightGraphicForAreaIndex(a.currentFeatureIndex),a._infographic._widget.setThisAreaTableRowHighlighted()))});m(a._infographic._widget.table,"mouseout",function(){a._thisAreasHighlightController.highlightGraphicForAreaIndex(null);a._infographic._widget.setTableRowHighlighted(null);b=null})}})},_applyTheme:function(a){this._infographic&&(d.set(this._infographic.domNode,"backgroundColor",a.style&&a.style.backgroundColor||
"transparent"),d.set(this._infographic.domNode,"fontFamily","inherit"))},_destroyCurrentInfographic:function(){this._showError(!1);this._infographic&&this._infographic.destroy();this._infographic=null},_filterRangesStats:null,_filterRanges:null,getFilterRanges:function(){return h(this._initPromise,function(){return(this._filterRangesStats=this._infographic.dataProvider.collectFilterRangesStats({excludeThisAreas:!0}))&&this._filterRangesStats.filterRanges}.bind(this))},setFilterRanges:function(a){this._filterRanges=
a;return h(this._initPromise,function(){this._infographic.dataProvider.setFilterRanges(a,{ignoreThisAreas:this._currentInfographicJson.type===c.ONE_VAR});this._infographic._widget.select?(this._infographic._widget.select.setFeatures(this._infographic.dataProvider.getData().features),this._infographic._widget.select.setDefaultValue({emitEvent:!0})):(this._infographic._widget.setDataProvider(this._infographic.dataProvider),this._doResize());this._syncWithShownFeatures();this._showEmptyView(!this.getNumAreasShown());
this.onContentUpdated()}.bind(this))},getNumAreasTotal:function(){return this._filterRangesStats&&this._filterRangesStats.numAreasTotal||0},getNumAreasShown:function(){if(this._currentInfographicJson.type===c.ONE_VAR)return this._infographic.dataProvider.getAllGeographyAttributes().length;if(this._infographic._widget.select)return this._infographic._widget.select.getNumFeatures&&this._infographic._widget.select.getNumFeatures()||0},_showEmptyView:function(a){k[a?"hide":"show"](this.infographicDiv);
k[a?"show":"hide"](this.noDataPlaceHolder);a&&this._syncEmptyViewPlaceholder()},_syncEmptyViewPlaceholder:function(){this.noDataPlaceHolder&&d.set(this.noDataPlaceHolder,"paddingTop",(this.height-d.get(this.noDataPlaceHolder,"height"))/2+"px")},notifyShown:function(){},width:null,height:null,_infographicResizedAtLeastOnce:!1,_hasScroll:!1,resize:function(a,b){if(void 0!==a){if(u.compareEqual(this.width,a,2)&&u.compareEqual(this.height,b,2))return;this.width=a;this.height=b}return B.invoke(this,"_doResize",
x.isPlayerOnServer?0:50)},_doResize:function(){var a=this;if(this._infographic&&this._infographic.domNode&&k.isNodeInLayout(this.domNode)&&this._currentInfographicJson){this._syncJsonDimensions();var b=this._currentInfographicJson.type,f=Math.max(function(){if(b===c.ONE_VAR){var e=n(".OneVarMultiComparison_Table",a.domNode)[0],e=e?d.get(e,"height")+120:0;return Math.max(e,g[b])}return b===c.TAPESTRY?(e=(e=n(".Tapestry_Main_Table",a.domNode)[0])?d.get(e,"height")+60:0,Math.max(e,g[b])):b===c.PRIZM5?
(e=(e=n(".Prizm5_Main_Table",a.domNode)[0])?d.get(e,"height")+60:0,Math.max(e,g[b])):b!==c.RELATED_VARS||a._infographic.expanded?g[b]:200}(),this.height);this._hasScroll=f>this.height;var h=this.width-(this._hasScroll?k.getScrollbarSize().w+3:0);d.set(this._infographic.domNode,{width:h+"px",height:f+"px"});d.set(this.viewDiv,{height:this.height+"px",overflowY:"auto"});this._infographic.resize();this._adjustErrorMessage();return A.delay()}},hasScroll:function(){return this._hasScroll},changeScroll:function(a,
b){this.domNode.scrollLeft+=a;this.domNode.scrollTop+=b},_syncJsonDimensions:function(){this._currentInfographicJson.style=this._currentInfographicJson.style||{};this._currentInfographicJson.style.width=this.width;this._currentInfographicJson.style.height=this.height},getPreferredHeight:function(){return this._infographic&&d.get(this._infographic.domNode,"height")},collapseContent:function(){this._infographic&&this._infographic.collapseContent()},getVisualState:function(){return{type:this._currentInfographicJson.type,
selectedFeatureId:this._infographic&&this._infographic.getSelectedFeatureID(),filterRanges:this._filterRanges?r.clone(this._filterRanges):null}},setVisualState:function(a){if(a){var b=this;return h(this._initPromise,function(){if(b._infographic)return h(a.filterRanges&&b.setFilterRanges(a.filterRanges),function(){return a.selectedFeatureId&&b._infographic.setSelectedFeatureID(a.selectedFeatureId)})})}},isMouseOver:function(){return C.isMouseOver(this.domNode)||this._infographic&&this._infographic._widget&&
this._infographic._widget.select&&this._infographic._widget.select.isMouseOver()},_showError:function(a){F.emulateErrors.contentErrors&&(a=!0);k[a?"show":"hide"](this.errorDiv);k[a?"hide":"show"](this.infographicDiv)},_adjustErrorMessage:function(){d.set(this.errorDiv,"paddingTop",d.get(this.domNode,"height")/2-20+"px")},toJson:function(){return r.clone(this._currentInfographicJson)},onContentUpdated:function(){},onShowWaiting:function(a){},_isCreated:function(){return this.domNode&&this._infographic&&
this._infographic.domNode},destroy:function(){this._stdPolygonsController&&this._stdPolygonsController.setShownFeatureAttributes([]);this._destroyCurrentInfographic();this.inherited(arguments)}});l.Infographic=t;return l});