// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/ObjectUtil",["dojo/number"],function(g){var c={};Math.log10=Math.log10||function(a){return Math.log(a)*Math.LOG10E};c.populateObject=function(a,b,d){function e(a,b){function f(f){var c=a[f],k=b[f],m=c&&"object"===typeof c;void 0!==c&&(void 0===k?b[f]=c:k&&"object"===typeof k&&m?e(c,k):d&&(m?(k=b[f]={},e(c,k)):b[f]=a[f]))}if(a&&b&&!(Array.isArray(a)&&!Array.isArray(b)||Array.isArray(b)&&!Array.isArray(a)))if(Array.isArray(a))a.forEach(function(a,b){f(b)});else for(var c in a)f(c)}
e(b,a);return a};c.filterByPattern=function(a,b){function d(a,b,e){for(var f in a){var c=a[f],h=b[f];if(Array.isArray(c)){var g=c[0];if(h&&Array.isArray(h)){var n=e[f]=[];h.forEach(function(a){if(a&&"object"===typeof a){var b=Array.isArray(a)?[]:{};d(g,a,b);n.push(b)}})}}else if("object"===typeof c){if(h&&"object"===typeof h){var l=e[f]={};d(c,h,l)}}else void 0!==h&&(e[f]=h)}}var e={};d(b,a,e);return e};c.traverseObject=function(a,b){for(var d in a){var e=a[d];b(e,d,a);e&&"object"===typeof e&&c.traverseObject(e,
b)}};c.copyOwnJsonProperties=function(a,b,d){b=b||{};for(var e in a){var f=a[e];a.hasOwnProperty(e)&&"function"!=typeof f&&(f&&"object"==typeof f&&d&&(f=d(e,f)),void 0!==f&&(b[e]=f))}return b};c.removeUndefinedProperties=function(a){a&&Object.keys(a).forEach(function(b){void 0===a[b]&&delete a[b]});return a};c.getValue=function(a,b){if("string"!==typeof b)return a;b=b.split(".");for(var d=0;d<b.length;d++)a=a&&a[b[d]];return a};c.setValue=function(a,b,d){if("string"===typeof b&&(b=b.split("."),b.length)){for(var e=
0;e<b.length-1;e++)a=a&&a[b[e]];a&&(a[b[b.length-1]]=d)}};c.isNumber=function(a){return!isNaN(parseFloat(a))&&isFinite(a)};c.roundNumber=function(a,b){return"number"!==typeof a?a:parseFloat(a.toFixed(void 0!==b?b:0))};c.getBestPrecision=function(a){return 0===a?0:Math.max(0,Math.round(Math.log10(3E3/Math.abs(a))))};c.getPlaces=function(a,b){function d(b,d){var c=a.indexOf(b,e);if(0>c)return f;b=a.charAt(c+b.length);return!b||0>d.indexOf(b)?f:c-e}a=+a;if(isNaN(a))return-1;a+="";var e=a.indexOf(".")+
1,f=e?a.length-e:0;if(2>=f||!b)return f;b=0;if(!+a.substr(0,e-1))for(;"0"===a.charAt(e);)e++,b++,f--;for(var c=f-1;2<=c;c--){var g=Math.min(d("000000000000000".substr(0,c),"01234"),d("999999999999999".substr(0,c),"56789"));if(g!==f){f=g;break}}return f+b};c.formatNumber=function(a,b){b="number"===typeof b?{places:b}:b||{};var d=b.places,e={};0<=d?e.places=d:d=-1;a=g.format(a,e);if(b.noSeparator){var e=c.getSeparator(),f;if(e)for(;0<=(f=a.indexOf(e));)a=a.substr(0,f)+a.substr(f+1)}if(b.preserveTrailingZeroes||
0>=d||!a)return a;for(b=a.length;0<d&&"0"==a.charAt(b-1);)b--,--d||b--;return a.substr(0,b)};c.formatNumberAsCurrency=function(a,b,d){return b?b.split(";")[0>a?1:0].replace("0",c.formatNumber(Math.abs(a),d)):c.formatNumber(a,d)};var l;c.getSeparator=function(){void 0===l&&(l=g.format(9999,{places:0}).replace(/9/g,""));return l};c.parseNumber=function(a,b,d,c){if(""===a)return"undefined"!==typeof d?d:NaN;if(null==a||"string"!==typeof a&&isNaN(a))return NaN;a=String(a);if(!a.trim())return void 0!==
d?d:NaN;d=g.parse(a,{strict:c});isNaN(d)&&a.trim().length&&(d=c?g.parse(a,{strict:c,locale:"en-US"}):Number(a));return isNaN(d)||void 0===b||0>b?d:g.round(d,b)};c.parsePercentOrCurrency=function(a,b,d,e,f){"string"===typeof a&&(a=a.replace("%",""),b&&(b=b.split(";")[0].replace("0",""),a=a.replace(b,"")));return c.parseNumber(a,d,e,f)};c.compareEqual=function(a,b,c){return void 0===c?a===b:Number(Number(a).toFixed(c))===Number(Number(b).toFixed(c))};return c});