// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/PopupUtil","dojo/_base/lang esri/dijit/geoenrichment/utils/onClickTouch dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style esri/dijit/geoenrichment/when esri/dijit/geoenrichment/ReportPlayer/config dijit/popup dijit/place dijit/Viewport ./DeviceUtil ./DnDUtil ./MouseUtil dojo/domReady!".split(" "),function(D,w,E,f,q,x,y,F,k,r,G,t,H,z){function I(a){if(!a)return["below"];var e=[];a.forEach(function(a){var c=q.isBodyLtr();switch(a){case "before-alt":c=
!c;case "after-alt":e.push(c?{aroundCorner:"BR",corner:"BL"}:{aroundCorner:"BL",corner:"BR"});e.push(c?{aroundCorner:"TR",corner:"TL"}:{aroundCorner:"TL",corner:"TR"});return}e.push(a)});return e}var h={makePopup:function(a,e,m,c){function r(b){if(c.overlay&&b._popupWrapper){var a=f.create("div",{"class":c.overlay.overlayClass});if(c.overlay.overlayParent)f.place(a,c.overlay.overlayParent);else{f.place(a,l,"before");var d=x.get(b._popupWrapper,"zIndex");x.set(a,"zIndex",d)}b.__popupOverlay=a}}function A(b){b.__popupOverlay&&
(f.destroy(b.__popupOverlay),b.__popupOverlay=null)}function B(b){n=!1;b.__bodyClickHandler&&b.__bodyClickHandler.remove();b.__bodyClickHandler=null;b.__popupWidgetOpenFlag=!1;A(b);c.onClose&&c.onClose()}function g(d){d&&c.stopEventPropagation&&d.stopPropagation();n||(n=!0,y(b||("function"==typeof a?a():a),function(a){b=a;b.domNode?(b.__openPopupWidgetFunc=g,l=k.moveOffScreen(b),y(c.onPreShow&&c.onPreShow(),function(){var a=I(c.orient);if(l&&!1!==c.allowAutoOrientation){var d=a.indexOf("below");-1!==
d&&-1===a.indexOf("above")&&a.splice(d+1,0,"above")}d=-1;if(-1!==a.indexOf("after")||-1!==a.indexOf("before"))var d=G.getEffectiveBox(this.ownerDocument),f=q.position(m,!1),d=Math.floor(Math.max(f.y+f.h,d.h-f.y))-10;c.noOverflow&&(b.baseClass="esriGENoOverflow "+b.baseClass);k.open({parent:e,popup:b,around:m,maxHeight:d,orient:a,onClose:function(){B(b)}});c.suppressReposition&&clearTimeout(k._aroundMoveListener);c.noOverflow&&(b.baseClass=b.baseClass.replace("esriGENoOverflow ",""));l&&c.wrapperClass&&
E.add(l,c.wrapperClass);b.__popupInfo=D.mixin({},k.getTopPopup());b.__popupInfo.orient=a;b.__popupInfo.around=m;A(b);r(b);c.onShow&&c.onShow();b.__popupWidgetOpenFlag=!0;p&&b.own&&b.own(p);b.__bodyClickHandler&&b.__bodyClickHandler.remove();if(!1!==c.closeOnClickOutside){var g="function"===typeof c.closeOnClickOutside?c.closeOnClickOutside:null;setTimeout(function(){b.__bodyClickHandler&&b.__bodyClickHandler.remove();b.__bodyClickHandler=w(document.body,t.isMobileDevice()?t.press:C,function(a){n&&
(z.fixTouchEvent(a),g&&!g(a)||z.isMouseOver(l)||c.isMouseOver&&c.isMouseOver()||b.isMouseOver&&b.isMouseOver()||b.__lockPopupWidgetFlag||h.close(b))})})}})):n=!1}))}if(a){if(F.isPlayerOnServer)return{remove:function(){}};c=c||{};var C=c.openMouseEvent?c.openMouseEvent:t.clickOrRelease,b="function"!==typeof a?a:null;if(b)var l=k.moveOffScreen(b);var n=!1;b&&(b.__openPopupWidgetFunc=g);var p;if(!1!==c.openOnMouseEvent){var u=g;if(c.toggleOnClick)var v,u=function(a){v=v||a.type;b?v===a.type&&h.toggle(b):
g()};p=!1===c.onClickComponent?null:void 0!==c.noDragClickTolerance?H.addNoDragClickHandler(c.onClickComponent||m,u,{tolerance:c.noDragClickTolerance}):w(c.onClickComponent||m,C,u)}c.openPopup&&g();return{remove:function(){b&&"function"!==typeof b&&(h.close(b),B(b),b._popupWrapper&&(b.domNode&&b.domNode.parentNode===b._popupWrapper&&b._popupWrapper.removeChild(b.domNode),f.destroy(b._popupWrapper),delete b._popupWrapper),delete b.__openPopupWidgetFunc,delete b.__popupWidgetOpenFlag);p&&p.remove()}}}},
setLocked:function(a,e){a.__lockPopupWidgetFlag=e},open:function(a){a&&!a.__lockPopupWidgetFlag&&!a.__popupWidgetOpenFlag&&a.__openPopupWidgetFunc&&a.__openPopupWidgetFunc()},close:function(a){a&&!a.__lockPopupWidgetFlag&&k.close(a)},isOpen:function(a){return!(!a||!a.__popupWidgetOpenFlag)},toggle:function(a){h.isOpen(a)?h.close(a):h.open(a)},refresh:function(a){if(a){a=a.__popupInfo;var e=q.isBodyLtr();a&&r.around(a.wrapper,a.around,a.orient,e)}},getWrapper:function(a){return a&&a._popupWrapper}};
return h});