// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/layers/ImageServiceLayerMixin","dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/json dojo/_base/config dojo/_base/connect dojo/has dojo/io-query dojo/DeferredList ../kernel ../config ../lang ../request ../deferredUtils ../urlUtils ../geometry/Extent ../geometry/Point ../geometry/Polygon ../renderers/colorRampUtils ./MosaicRule ./RasterFunction ./DimensionalDefinition ./Raster ./PixelBlock ./pixelFilters/VectorFieldPixelFilter ./rasterFormats/ImageCanvasDecoder ./TimeInfo ./Field ../graphic ../tasks/ImageServiceIdentifyTask ../tasks/ImageServiceIdentifyParameters".split(" "),
function(J,f,l,n,q,D,N,Q,R,ea,S,T,E,x,m,L,K,U,V,W,C,y,O,X,M,P,Y,Z,aa,ba,ca,da){J=J(null,{declaredClass:"esri.layers.ImageServiceLayerMixin",_rasterFieldPrefix:"Raster.",_renderingRuleFieldSubPrefix:"ServicePixelValue.",_rasterFunctionServiceInfoProps:"bandCount pixelType hasRasterAttributeTable hasColormap hasHistograms minValues maxValues meanValues stdvValues serviceDataType".split(" "),_pixelTypeRanges:{U1:[0,1],U2:[0,3],U4:[0,15],U8:[0,255],S8:[-128,127],U16:[0,65535],S16:[-32768,32767]},_eventMap:{"rendering-change":!0,
"mosaic-rule-change":!0,"spatial-reference-change":!0,"renderer-change":!0},_cachedVariableStats:{},constructor:function(a,b){this.useMapTime=b&&b.hasOwnProperty("useMapTime")?!!b.useMapTime:!0},_initialize:function(a,b){this._url=L.urlToObject(a);this.raster=new X(this._url.path);this._rasterFunctionTemplateInfos={};this._customRenderingRuleId={};this.infoTemplate=b&&b.infoTemplate;this.format=(a=b&&b.imageServiceParameters)&&a.format;this.compressionTolerance=a&&a.compressionTolerance?a.compressionTolerance:
.01;this.interpolation=a?a.interpolation:null;this.compressionQuality=a?a.compressionQuality:null;this.bandIds=a?a.bandIds:null;this.mosaicRule=a?a.mosaicRule:null;this.renderingRule=a?a.renderingRule:null;this.renderer=a?a.renderer:null;this.useMapDimensionValue=b&&b.hasOwnProperty("useMapDimensionValue")?!!b.useMapDimensionValue:!0;this.hasImageFilter=b&&b.hasImageFilter;this.activeMapDimensions=b&&b.activeMapDimensions;this._params=f.mixin({},this._url.query,{f:"image",interpolation:this.interpolation,
format:this.format,compressionQuality:this.compressionQuality,bandIds:this.bandIds?this.bandIds.join(","):null},a?a.toJson():{});this.pixelFilter=b&&b.pixelFilter;this.originalPixelData=this.pixelData=null;this.hasDataChanged=!0;this._requestDataHandler=f.hitch(this,this._requestDataHandler);this._requestDataErrorHandler=f.hitch(this,this._requestDataErrorHandler);this._rasterReadPromise=null;this._initLayer=f.hitch(this,this._initLayer);this._queryVisibleRastersHandler=f.hitch(this,this._queryVisibleRastersHandler);
this._visibleRasters=[];this._rasterAttributeTableFields=[];this._rasterAttributeTableFeatures=[];this._renderingRuleAttributeTable={};this._renderingRuleColormap={};this._useRenderingRuleAttributeTable=!1;this._loadCallback=b&&b.loadCallback;a&&a.renderer&&(a.renderer.outputUnit||a.renderer.inputUnit)&&(this.vectorFieldPixelFilter=new P,this.vectorFieldPixelFilter.setUnits(a.renderer.inputUnit,a.renderer.outputUnit));(b=b&&b.resourceInfo)?this._initLayer(b):x({url:this._url.path,content:f.mixin({f:"json"},
this._url.query),callbackParamName:"callback",load:this._initLayer,error:this._errorHandler});this.registerConnectEvents()},disableClientCaching:!1,_initLayer:function(a,b){if(null!==a&&void 0!==a){this._findCredential();(this.credential&&this.credential.ssl||a&&a._ssl)&&this._useSSL();b=this.minScale;var c=this.maxScale;f.mixin(this,a);this.minScale=b;this.maxScale=c;this.initialExtent=this.fullExtent=this.extent=new K(a.extent);this.spatialReference=this.initialExtent.spatialReference;this.pixelSizeX=
parseFloat(this.pixelSizeX);this.pixelSizeY=parseFloat(this.pixelSizeY);var d=this.minValues,e=this.maxValues,g=this.meanValues,h=this.stdvValues,A=this.bands=[];b=0;for(c=this.bandCount;b<c;b++)A[b]={min:d[b],max:e[b],mean:g[b],stddev:h[b]};this.timeInfo=(b=this.timeInfo)&&b.timeExtent?new Z(b):null;c=this.fields=[];if(d=a.fields)for(b=0;b<d.length;b++)c.push(new aa(d[b]));this._updateInfoTemplateFields(this.fields);this.version=a.currentVersion;this.version||(this.version="fields"in a||"objectIdField"in
a||"timeInfo"in a?10:9.3);E.isDefined(a.minScale)&&!this._hasMin&&"Raster"!==a.cacheType&&this.setMinScale(a.minScale);E.isDefined(a.maxScale)&&!this._hasMax&&"Raster"!==a.cacheType&&this.setMaxScale(a.maxScale);b={};a.defaultMosaicMethod?(b.method=a.defaultMosaicMethod,b.operation=a.mosaicOperator,b.sortField=a.sortField,b.sortValue=a.sortValue):b.method=C.METHOD_NONE;this.defaultMosaicRule=new C(b);this.defaultMosaicRule.ascending=!0;this._useRenderingRuleAttributeTable=10<this.version&&"esriImageServiceDataTypeThematic"===
this.serviceDataType;this._setDefaultRenderingRule(!0);this._getRenderingRuleAttributeTableAndColormap();this._isScientificData()&&(!this.mosaicRule||this.mosaicRule&&!this.mosaicRule.multidimensionalDefinition)&&this._setDefaultMultidimensionalDefinition(!0);10<this.version&&this.hasRasterAttributeTable&&this.getRasterAttributeTable().then(f.hitch(this,function(a){a&&(a.features&&a.fields&&(this.rasterAttributeTable=f.clone(a)),a.features&&0<a.features.length&&(this._rasterAttributeTableFeatures=
f.clone(a.features)),a.fields&&0<a.fields.length&&(this._rasterAttributeTableFields=f.clone(a.fields)),this.renderingRule||!this.renderer||"esri.renderer.ClassBreaksRenderer"!==this.renderer.declaredClass&&"esri.renderer.UniqueValueRenderer"!==this.renderer.declaredClass||this.refresh())}));this._initVectorPixelFilter();this.bandIds||2!==this.bandCount||this.renderingRule||"esri.layers.ArcGISImageServiceLayer"!==this.declaredClass||this.setBandIds([0,0,0],!0);10.3<=this.version&&this.rasterFunctionInfos&&
this.rasterFunctionInfos.length&&this.getRasterFunctionInfos().then(f.hitch(this,function(a){if(a&&a.length){this.rasterFunctionInfos=a;var b=[],c;n.forEach(a,function(a){if(a){var d=a.functionType;c=c||1===d||2===d;b.push(a.name)}},this);this._hasItemLevelRFT=c;this._rasterFunctionNames=b;c&&(this._initVectorPixelFilter(),this.refresh())}}));this.loaded=!0;this._setDefaultFilter();this.onLoad(this);if(a=this._loadCallback)delete this._loadCallback,a(this)}},_updateInfoTemplateFields:function(a){if(a&&
!(1>a.length)&&this.infoTemplate&&this.infoTemplate.info&&this.infoTemplate.info.fieldInfos&&!(1>this.infoTemplate.info.fieldInfos.length)){var b,c,d,e;e=this.infoTemplate.info.fieldInfos;for(b=0;b<a.length;b++)for(d=a[b],c=0;c<e.length;c++)if(e[c].fieldName.toLowerCase()===d.name.toLowerCase()&&e[c].fieldName!==d.name){e[c].fieldName=d.name;break}}},getKeyProperties:function(a){var b=this._url.path+"/keyProperties",c=new l(m._dfdCanceller),d={f:"json"};a&&a.renderingRule&&(d.renderingRule=q.toJson(a.renderingRule.toJson()));
10<this.version?(c._pendingDfd=x({url:b,content:d,handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(a){c.callback(a)},function(a){c.errback(a)})):(a=Error("Layer does not have key properties"),a.log=!!D.isDebug,c.errback(a));return c},getRasterAttributeTable:function(a){var b=this._url.path+"/rasterAttributeTable",c=new l(m._dfdCanceller),d={f:"json"},e=this.hasRasterAttributeTable;a&&a.renderingRule&&(d.renderingRule=q.toJson(a.renderingRule.toJson()),e=!0);!this.loaded||
10<this.version&&e?(c._pendingDfd=x({url:b,content:d,handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(a){c.callback(a)},function(a){c.errback(a)})):(a=Error("Layer does not support raster attribute table"),a.log=!!D.isDebug,c.errback(a));return c},getRenderingRuleAttributeTable:function(a){var b=new l(m._dfdCanceller);if(!a||!a.renderingRule)return b.errback(Error("Rendering rule is not specified")),b;a=a.renderingRule;var c=this._getRenderingRuleId(a);this._renderingRuleAttributeTable&&
c&&this._renderingRuleAttributeTable.hasOwnProperty(c)?b.resolve(this._renderingRuleAttributeTable[c]):b=this.getRasterAttributeTable({renderingRule:a}).then(f.hitch(this,function(a){var b;a&&a.features&&a.features.length&&a.fields&&a.fields.length&&(b={features:f.clone(a.features),fields:f.clone(a.fields)},c&&(this._renderingRuleAttributeTable[c]=b));return b}));return b},_initVectorPixelFilter:function(){var a;this._hasItemLevelRFT&&this.renderingRule&&(a=this._getItemLevelRenderingRule(this.renderingRule));
if(a=a||this.renderingRule)return this.getRenderingRuleServiceInfo(a).then(f.hitch(this,function(a){!a||!this._isVectorData(a)&&"esri.layers.ArcGISImageServiceVectorLayer"!==this.declaredClass||E.isDefined(this.pixelFilter)||(this.vectorFieldPixelFilter=this.vectorFieldPixelFilter||new P,this.vectorFieldPixelFilter.isDataUV="esriImageServiceDataTypeVector-UV"===a.serviceDataType,this.pixelFilter=this.vectorFieldPixelFilter.computeMagnitudeAndDirection,this.getKeyProperties().then(f.hitch(this,this._setFlowRepresentation)),
this._applyVectorResamplingType(a.serviceDataType))}))},_applyVectorResamplingType:function(a){if(a){var b=this.renderingRule;b&&"Resample"===b.functionName&&((b.functionArguments||{}).ResamplingType="esriImageServiceDataTypeVector-UV"===a?7:10,this.setRenderingRule(new y(b.toJson())))}},_getRasterAttributeTableFeatures:function(){var a=new l;if(this._rasterAttributeTableFeatures&&0<this._rasterAttributeTableFeatures.length)return a.resolve(this._rasterAttributeTableFeatures),a;if(10<this.version&&
this.hasRasterAttributeTable)return a=this.getRasterAttributeTable(),a.then(f.hitch(this,function(a){a&&a.features&&0<a.features.length&&(this._rasterAttributeTableFeatures=f.clone(a.features))})),a;a.resolve(this._rasterAttributeTableFeatures);return a},_getRenderingRuleAttributeTableFeatures:function(a){a=a&&a.renderingRule;return a?this.getRenderingRuleAttributeTable({renderingRule:a}).then(function(a){return a&&a.features}):(a=new l,a.errback(Error("Rendering rule is not specified")),a)},_getRenderingRuleAttributeTableAndColormap:function(){this.renderingRule&&
this.getRenderingRuleServiceInfo(this.renderingRule).then(f.hitch(this,function(a){a.hasRasterAttributeTable&&this.getRenderingRuleAttributeTable({renderingRule:this.renderingRule}).then(f.hitch(this,function(){!this.renderer||"esri.renderer.ClassBreaksRenderer"!==this.renderer.declaredClass&&"esri.renderer.UniqueValueRenderer"!==this.renderer.declaredClass||this.refresh()}));a.hasColormap&&this.getRenderingRuleColormap({renderingRule:this.renderingRule}).then(f.hitch(this,function(){this.renderer&&
"esri.renderer.ColormapRenderer"===this.renderer.declaredClass&&this.refresh()}))}))},getCustomRasterFields:function(a){var b=a?a.rasterAttributeTableFieldPrefix:this._rasterFieldPrefix;a=10.3<=this.version?"esriFieldTypeDouble":"esriFieldTypeString";var c={name:this._rasterFieldPrefix+"ItemPixelValue",alias:"Item Pixel Value",domain:null,editable:!1,length:50,type:a},d={name:this._rasterFieldPrefix+"ServicePixelValue",alias:"Service Pixel Value",domain:null,editable:!1,length:50,type:a},e={name:this._rasterFieldPrefix+
"ServicePixelValue.Raw",alias:"Raw Service Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeDouble"},g=this.fields?f.clone(this.fields):[];a=g.length;g[a]=d;10.4<=this.version&&"esri.layers.ArcGISImageServiceLayer"===this.declaredClass&&(!this.rasterFunctionInfos||!this.rasterFunctionInfos.length||this._isRenderingRuleAProcessingTemplate({functionName:"none"}))&&(a++,g[a]=e);if(this.capabilities&&-1<this.capabilities.toLowerCase().indexOf("catalog")||this.fields&&0<this.fields.length)a++,
g[a]=c;!E.isDefined(this.pixelFilter)||"esriImageServiceDataTypeVector-UV"!==this.serviceDataType&&"esriImageServiceDataTypeVector-MagDir"!==this.serviceDataType||(c={name:this._rasterFieldPrefix+"Magnitude",alias:"Magnitude",domain:null,editable:!1,type:"esriFieldTypeDouble"},d={name:this._rasterFieldPrefix+"Direction",alias:"Direction",domain:null,editable:!1,type:"esriFieldTypeDouble"},a++,g[a]=c,a++,g[a]=d);a=this._rasterAttributeTableFields;(c=this.renderingRule&&this._getRenderingRuleId(this.renderingRule))&&
this._renderingRuleAttributeTable&&this._renderingRuleAttributeTable.hasOwnProperty(c)&&(a=this._renderingRuleAttributeTable[c].fields);a&&0<a.length&&(a=n.filter(a,function(a){return"esriFieldTypeOID"!==a.type&&"value"!==a.name.toLowerCase()}),a=n.map(a,function(a){var c=f.clone(a);c.name=b+a.name;return c}),g=g.concat(a));var h=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;10.4<=this.version&&this.rasterFunctionInfos&&n.forEach(this.rasterFunctionInfos,function(a){a&&a.name&&"none"!==
a.name.toLowerCase()&&(a={name:h+a.name.replace(/ /gi,"_"),alias:a.name,domain:null,editable:!1,type:"esriFieldTypeDouble"},g.push(a))});return g},_applyTimeToMultidimensionalCRF:function(a,b){var c=this._isTimeSupportedOnCRF();if(c&&(!a||!a.multidimensionalDefinition))return a;var d=this.timeInfo&&this.timeInfo.startTimeField;if((b=b||this._params.time)&&d&&this._isMultidimensionalCRF()){a=f.clone(a||this.defaultMosaicRule)||new C;a.multidimensionalDefinition=a.multidimensionalDefinition||[];var e=
a.multidimensionalDefinition.filter(function(a){return a.dimensionName===d}),g=b.split(",").map(function(a){return parseInt(a,10)});2===g.length&&g[0]===g[1]&&(g.length=1);0<e.length?c?a.multidimensionalDefinition.forEach(function(a){a.dimensionName===d&&(a.dimensionName=null,a.isSlice=null,a.values=null)}):a.multidimensionalDefinition.forEach(function(a){a.dimensionName===d&&(a.isSlice=1===g.length,a.values=1===g.length?g:[g])}):c||(a.multidimensionalDefinition.some(function(a){return null!=a.variableName&&
null==a.dimensionName})?a.multidimensionalDefinition.forEach(function(a){null!=a.variableName&&null==a.dimensionName&&(a.dimensionName=d,a.isSlice=1===g.length,a.values=1===g.length?g:[g])}):a.multidimensionalDefinition.push(new O({variableName:"",dimensionName:d,isSlice:1===g.length,values:1===g.length?g:[g]})));this._cleanupMultidimensionalDefinition(a)}return a},_prepareGetImageParameters:function(a,b,c,d){d=E.isDefined(d)?d:this._params;if(this.renderer||this._hasItemLevelRFT&&this.renderingRule){var e=
this.getExportImageRenderingRule();d.renderingRule=e?q.toJson(e.toJson()):null}e=this.getExportImageMosaicRule(d);d.mosaicRule=e?q.toJson(e.toJson()):null;e=a.spatialReference.wkid||q.toJson(a.spatialReference.toJson(!1));delete d._ts;f.mixin(d,{bbox:a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,imageSR:e,bboxSR:e,size:b+","+c},this.disableClientCaching?{_ts:(new Date).getTime()}:{});delete d.compressionTolerance;d.format&&"LERC"===d.format.toUpperCase()&&(d.compressionTolerance=this.compressionTolerance);
d.token=this._getToken()},getImageUrl:function(a,b,c,d,e){e=E.isDefined(e)?e:this._params;this._prepareGetImageParameters(a,b,c,e);a=f.clone(e);this._cleanupRequestParams(a);b=this._url.path+"/exportImage?";c=L.addProxy(b+R.objectToQuery(f.mixin(a,{f:"image"})));var g=a.token;c.length>T.defaults.io.postLength||this.useMapImage?this._jsonRequest=x({url:b,content:f.mixin(a,{f:"json"}),callbackParamName:"callback",load:function(a,b){a=a.href;g&&(a+=-1===a.indexOf("?")?"?token\x3d"+g:"\x26token\x3d"+
g);d(L.addProxy(a))},error:this._errorHandler}):d(c)},onRenderingChange:function(){},onMosaicRuleChange:function(){},onRendererChange:function(){},setInterpolation:function(a,b){this.interpolation=this._params.interpolation=a;b||this.refresh(!0)},setCompressionQuality:function(a,b){this.compressionQuality=this._params.compressionQuality=a;b||this.refresh(!0)},setCompressionTolerance:function(a,b){this.compressionTolerance=a;b||this.refresh(!0)},setBandIds:function(a,b){var c=!1;this.bandIds!==a&&
(c=!0);this.bandIds=a;this._params.bandIds=a.join(",");if(c&&!b)this.onRenderingChange();b||this.refresh(!0)},setDefaultBandIds:function(a){this.bandIds=this._params.bandIds=null;a||this.refresh(!0)},setDisableClientCaching:function(a){this.disableClientCaching=a},setMosaicRule:function(a,b){var c=!1;this.mosaicRule!==a&&(c=!0);this.mosaicRule=a;this._params.mosaicRule=q.toJson(a.toJson());if(c&&!b)this.onMosaicRuleChange();b||this.refresh(!0)},getRasterFunctionInfos:function(){if(10.3>this.version||
!this.rasterFunctionInfos||!this.rasterFunctionInfos.length)console.log("Layer doesn't support /rasterFunctionInfos resource.");else return x({url:this._url.path+"/rasterFunctionInfos",content:{f:"json"},handleAs:"json",load:function(a){return a&&a.rasterFunctionInfos}})},setRenderingRule:function(a,b){var c=!1;this.renderingRule!==a&&(c=!0);this.renderingRule=a;this._params.renderingRule=a?q.toJson(a.toJson()):null;this._useRenderingRuleAttributeTable?this.getRenderingRuleAttributeTable({renderingRule:a}):
"esri.layers.RasterXLayer"!==this.declaredClass&&this._getRenderingRuleAttributeTableAndColormap();if(c)this.onRenderingChange();this._setDefaultFilter();b||this.refresh(!0)},setImageFormat:function(a,b){this.format=this._params.format=a;this._setDefaultFilter();b||this.refresh(!0)},setInfoTemplate:function(a){this.infoTemplate=a;this._updateInfoTemplateFields(this.fields)},setDefinitionExpression:function(a,b){var c=this.mosaicRule?this.mosaicRule.toJson():{};this.mosaicRule||(this.defaultMosaicRule?
c=this.defaultMosaicRule.toJson():c.method=C.METHOD_NONE);c.where=a;a=new C(c);this.setMosaicRule(a,b);return this},getDefinitionExpression:function(){return this.mosaicRule?this.mosaicRule.where:null},setPixelFilter:function(a){this.pixelFilter=a;this._isDefaultPixelFilter=!1},getPixelData:function(a){return a?(this._useBrowserDecoding()&&(this.originalPixelData={pixelBlock:this._getPixelBlockFromCanvas(this._context,this._map.width,this._map.height),extent:this._map.extent}),this.originalPixelData):
this.pixelData},getExportImageRenderingRule:function(){var a;this._hasItemLevelRFT&&this.renderingRule&&(a=this._getServiceLevelRenderingRule(this.renderingRule));a=a||this.renderingRule;this._isItemLevelRasterFunction(this.renderingRule)&&(a=void 0);return this._combineRenderingRule(this._convertRendererToRenderingRule(this.renderer),a)},getExportImageMosaicRule:function(){var a=this.mosaicRule,b;this._hasItemLevelRFT&&this.renderingRule&&(b=this._getItemLevelRenderingRule(this.renderingRule));b&&
(a=a||this.defaultMosaicRule||new C,a.itemRenderingRule=b);return a=this._applyTimeToMultidimensionalCRF(a)},redraw:function(){this.hasDataChanged=!1;this._setPixelData(this.originalPixelData)},getHistograms:function(){var a=new l(m._dfdCanceller);if(this.hasHistograms)a._pendingDfd=x({url:this._url.path+"/histograms",content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),a._pendingDfd.then(function(b){a.callback(b)},function(b){a.errback(b)});else{var b=Error("Layer does not have histograms.");
b.log=!!D.isDebug;a.errback(b)}return a},computeHistograms:function(a){var b=new l(m._dfdCanceller);if(10.1<=this.currentVersion){a=a||{};var c=a.geometry||this.fullExtent,d=(a.geometry||this.fullExtent).toJson(),c="extent"===c.type?"esriGeometryEnvelope":"esriGeometryPolygon",e=a.renderingRule||this.renderingRule||this.defaultRenderingRule,e=e?e.toJson():null,g=a.mosaicRule||this.mosaicRule||this.defaultMosaicRule,g=g?g.toJson():null;a=a.pixelSize||{x:this.pixelSizeX,y:this.pixelSizeY};b._pendingDfd=
x({url:this._url.path+"/computeHistograms",content:f.mixin({f:"json",geometry:JSON.stringify(d),geometryType:c,renderingRule:JSON.stringify(e),mosaicRule:JSON.stringify(g),pixelSize:JSON.stringify(a),callbackParamName:"callback"}),handleAs:"json"});b._pendingDfd.then(function(a){b.callback(a)},function(a){b.errback(a)})}else d=Error("Layer doesn't support computeHistograms."),d.log=!!D.isDebug,b.errback(d);return b},getRenderingRuleServiceInfo:function(a,b){function c(a){return a.name&&a.arguments&&
a.function&&a.hasOwnProperty("functionType")}var d=new m._fixDfd(new l(m._dfdCanceller));if(!a)return d.errback(Error("Rendering rule is not specified")),d;if(!c(a)){var e=this._getRenderingRuleId(a);if(e&&this._rasterFunctionTemplateInfos[e])return d.resolve(this._rasterFunctionTemplateInfos[e]),d}return x({url:this._url.path,content:f.mixin(f.mixin({f:"json",renderingRule:JSON.stringify(a.toJson())},this._url.query)),callbackParamName:"callback",load:f.hitch(this,function(b){var d={};n.forEach(this._rasterFunctionServiceInfoProps,
function(a){d[a]=b[a]});c(a)||(this._rasterFunctionTemplateInfos[e]=d);return d}),error:b||this._errorHandler})},queryVisibleRasters:function(a,b,c,d){var e=this._map,g=m._fixDfd(new l(m._dfdCanceller));this._visibleRasters=[];var h,A,p=!0,r=!0,k=null,B=this.infoTemplate?this.infoTemplate.info:null,t=B?f.clone(this.infoTemplate.info.fieldInfos):null;b=b||{};if(B&&this.infoTemplate.info.mediaInfos&&this.infoTemplate.info.mediaInfos.length){var v=[];n.forEach(this.infoTemplate.info.mediaInfos,function(a){v=
v.concat(a&&a.value&&a.value.fields||[])});v.length&&n.forEach(t,function(a){a&&-1<v.indexOf(a.fieldName)&&(a.visible=!0)})}if(t&&0<t.length)for(p=!1,h=0;h<t.length;h++)if((A=t[h])&&A.fieldName.toLowerCase()!==this._rasterFieldPrefix.toLowerCase()+"servicepixelvalue"&&(A.visible||B.title&&-1<B.title.toLowerCase().indexOf(A.fieldName.toLowerCase()))){p=!0;break}this.infoTemplate&&this.infoTemplate.info&&this.infoTemplate.info.layerOptions&&this.infoTemplate.info.layerOptions.hasOwnProperty("returnTopmostRaster")&&
(k=this.infoTemplate.info.layerOptions.returnTopmostRaster?1:null);t&&0<t.length&&(r=!1,n.some(t,function(a){if(a&&a.fieldName.toLowerCase()===this._rasterFieldPrefix.toLowerCase()+"itempixelvalue"&&a.visible)return r=!0},this));var w=(A=this._removeVisualizationStretchFunction(this.renderingRule))&&A.functionName,u=[];if(10.4<=this.version){var G=!1;if(this.rasterFunctionInfos&&t){var q=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;n.forEach(this.rasterFunctionInfos,function(a){var b=
q+a.name.replace(/ /gi,"_");n.some(t,function(a){return a.visible&&a.fieldName===b})&&(G=G||w&&w===a.name,u.push(new y({rasterFunction:a.name})))})}A&&!G&&u.push(A)}h=new da;h.geometry=a.geometry;h.returnGeometry=this._map.spatialReference.equals(this.spatialReference);h.returnCatalogItems=p;h.timeExtent=this.timeInfo?a.timeExtent:null;h.returnPixelValues=r;h.maxItemCount=k||a.maxItemCount;this._params.time&&this.mosaicRule?(a=f.clone(this.mosaicRule),a=this._filterOutTimeDimension(a),h.mosaicRule=
a):h.mosaicRule=this.mosaicRule||null;this._isMultidimensionalCRF()&&h.timeExtent&&(h.mosaicRule=this._applyTimeToMultidimensionalCRF(h.mosaicRule,h.timeExtent.toJson().join(",")),this._isTimeSupportedOnCRF()||delete h.timeExtent);h.renderingRule=10.4>this.version&&A||null;h.renderingRules=u||null;10.8>this.version&&(h.returnPixelValues=void 0,h.maxItemCount=void 0);e&&(e=new U((e.extent.xmax-e.extent.xmin)/e.width,(e.extent.ymax-e.extent.ymin)/e.height,e.extent.spatialReference),h.pixelSize=e);b.requestParams=
h;var x=this,e=new ca(this.url);(g._pendingDfd=e.execute(h)).addCallbacks(function(a){x._queryVisibleRastersHandler(a,b,c,d,g)},function(a){x._resolve([a],null,d,g,!0)});return g},_queryVisibleRastersHandler:function(a,b,c,d,e){function g(){var a=this.getCustomRasterFields(b),d=this._getDomainFields(a),g=b?b.returnDomainValues:!1,t=b&&b.rasterAttributeTableFieldPrefix,k,B,v,w,u,l,m,q,x,y,a=(a=this._getRenderingRuleId(this.renderingRule))&&this._rasterFunctionTemplateInfos[a];this.renderingRule&&(this._useRenderingRuleAttributeTable||
a)?(a=this._getRenderingRuleAttributeTableFeatures({renderingRule:this.renderingRule}),this.hasRasterAttributeTable||(y=h)):a=this._getRasterAttributeTableFeatures();a.then(f.hitch(this,function(a){for(k=0;k<r.length;k++){z=r[k];z.setInfoTemplate(this.infoTemplate);z._layer=this;if(h){x=h.replace(/ /gi,"").split(",");B=h;v=x;p&&p.length>=k&&(B=p[k].replace(/ /gi,", "),v=p[k].split(" "));z.attributes[this._rasterFieldPrefix+"ItemPixelValue"]=v;z.attributes[this._rasterFieldPrefix+"ServicePixelValue"]=
x;A&&(z.attributes[this._rasterFieldPrefix+"ServicePixelValue.Raw"]=A.replace(/ /gi,"").split(","));if(this.pixelFilter){var b=new M({height:1,width:1,pixelType:"F32",pixels:[],statistics:[]});n.forEach(v,function(a){b.addData({pixels:[a],statistics:{minValue:a,maxValue:a,noDataValue:null}})});this.pixelFilter({pixelBlock:b,extent:new K(0,0,0,0,this._map.spatialReference)});if("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType)z.attributes[this._rasterFieldPrefix+
"Magnitude"]=b.pixels[0][0],z.attributes[this._rasterFieldPrefix+"Direction"]=b.pixels[1][0]}n.forEach(G,function(a){z.attributes[a.name]=a.value});var C;C=0<this.fields.length?y||B:y||A;if(a&&0<a.length&&(w=n.filter(a,function(a){if(a&&a.attributes)return a.attributes.hasOwnProperty("Value")?a.attributes.Value==C:a.attributes.VALUE==C}),0<w.length&&(u=f.clone(w[0]),t&&u))){q={};for(l in u.attributes)u.attributes.hasOwnProperty(l)&&(m=t+l,q[m]=u.attributes[l]);u.attributes=q;z.attributes=f.mixin(z.attributes,
u.attributes)}}g&&d&&0<d.length&&n.forEach(d,function(a){if(a){var b=z.attributes[a.name];E.isDefined(b)&&(b=this._getDomainValue(a.domain,b),E.isDefined(b)&&(z.attributes[a.name]=b))}},this);I.push(z);this._visibleRasters.push(z)}this._resolve([I,null,!0],null,c,e)}))}var h=a.value,A=a.value,p,r,k=0,B=0,t=this,v=this.objectIdField,w,u,G=[];d=b.requestParams.renderingRules;var l=a.processedValues,m=this.renderingRule&&q.toJson(this._removeVisualizationStretchFunction(this.renderingRule).toJson());
if(d&&l&&d.length===l.length){var y=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;n.forEach(d,function(a,b){if(a.functionName){var c={name:y+a.functionName.replace(/ /gi,"_"),value:l[b].replace(/ /gi,"").split(",")};G.push(c);m&&m===q.toJson(a.toJson())&&(h=l[b])}})}d=this.infoTemplate&&this.infoTemplate.info&&this.infoTemplate.info.layerOptions&&this.infoTemplate.info.layerOptions.hasOwnProperty("showNoDataRecords")?this.infoTemplate.info.layerOptions.showNoDataRecords:!0;if(a.catalogItems){var C=
0,D,H,F=a.catalogItems.features.length;u=0;r=Array(F);p=Array(F);w=Array(F);if(a.properties&&a.properties.Values){F=a.properties.Values.length;for(k=0;k<F;k++)-1<a.properties.Values[k].toLowerCase().indexOf("nodata")&&u++;D=F-u;for(k=0;k<F;k++)u=!0,-1<a.properties.Values[k].toLowerCase().indexOf("nodata")?(H=D++,d||(u=!1,r.length--,p.length--,w.length--)):H=C++,u&&(r[H]=a.catalogItems.features[k],p[H]=a.properties.Values[k],w[H]=r[H].attributes[v])}else{for(k=0;k<F;k++)r[k]=a.catalogItems.features[k],
w[k]=r[k].attributes[v];p=null}}this._visibleRasters=[];var z;(a=-1<h.toLowerCase().indexOf("nodata"))&&!d&&(r=[],p=[],w=[]);!h||r||a||(v="ObjectId",r=[],z=new ba(new K(this.fullExtent),null,{ObjectId:0}),r.push(z));var I=[];r?!this._map.spatialReference.equals(this.spatialReference)&&w&&0<w.length?x({url:this._url.path+"/query",content:{f:"json",objectIds:w.join(","),returnGeometry:!0,outSR:q.toJson(t._map.spatialReference.toJson()),outFields:v},handleAs:"json",callbackParamName:"callback",load:function(a){if(0===
a.features.length)t._resolve([I,null,null],null,c,e);else{for(k=0;k<a.features.length;k++)for(B=0;B<r.length;B++)r[B].attributes[v]==a.features[k].attributes[v]&&(r[B].geometry=new V(a.features[k].geometry),r[B].geometry.setSpatialReference(t._map.spatialReference));g.call(t)}},error:function(a){t._resolve([I,null,null],null,c,e)}}):g.call(this):this._resolve([I,null,null],null,c,e)},getVisibleRasters:function(){var a=this._visibleRasters,b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(a[c]);return b},
_getDomainFields:function(a){if(a){var b=[];n.forEach(a,function(a){if(a.domain){var c={};c.name=a.name;c.domain=a.domain;b.push(c)}});return b}},_getDomainValue:function(a,b){if(a&&a.codedValues){var c;n.some(a.codedValues,function(a){return a.code===b?(c=a.name,!0):!1});return c}},_requestData:function(a,b,c){this._rasterReadPromise&&this._rasterReadPromise.cancel();a=f.clone(a);var d=a._normalize(!0);this._prepareGetImageParameters(d,b,c);b=f.clone(this._params);this._cleanupRequestParams(b);b.extent=
a;b.format=b.format||(10.3<=this.version?"lerc":"jpgpng");"lerc"===b.format.toLowerCase()&&!b.lercVersion&&10.5<=this.version&&(b.lercVersion=2);this._params.time&&this._isMultidimensionalCRF()&&!this._isTimeSupportedOnCRF()&&delete b.time;c=null;this._useBrowserDecoding()&&(c=new Y({ctx:this._context}));b={imageServiceParameters:b,nBands:Math.min(this.bandCount,3),pixelType:this.pixelType,decodeFunc:c?f.hitch(c,"decode"):null};this._rasterReadPromise=this.raster.read(b,this._requestDataHandler,this._requestDataErrorHandler)},
_requestDataHandler:function(a){this._rasterReadPromise&&this._rasterReadPromise.isCanceled()||(this.originalPixelData=a,this.hasDataChanged=!0,this._setPixelData(a))},_setPixelData:function(a){a=this._clonePixelData(a);this.pixelFilter&&this.pixelFilter(a);this.pixelData=a;this._rasterReadPromise&&this._rasterReadPromise.isCanceled()||(this._drawPixelData(),this._rasterReadPromise=null)},_clonePixelData:function(a){if(null===a||void 0===a)return a;var b={};a.extent&&(b.extent=f.clone(a.extent));
a=a.pixelBlock;if(null===a||void 0===a)return b;b.pixelBlock=a.clone();return b},_setDefaultFilter:function(){},_getPixelBlockFromCanvas:function(a,b,c){a=a.getImageData(0,0,b,c).data;for(var d=b*c,e=0,g=0,h=new Uint8Array(d),f=new Uint8Array(d),p=new Uint8Array(d),r=new Uint8Array(d),k=Infinity,n=Infinity,t=Infinity,v=-Infinity,w=-Infinity,u=-Infinity,l,m,q,e=0;e<d;e++)l=a[g++],m=a[g++],q=a[g++],k=k<l?k:l,v=v>l?v:l,n=n<m?n:m,w=w>m?w:m,t=t<q?t:q,u=u>q?u:q,h[e]=l,f[e]=m,p[e]=q,r[e]=a[g++]&1;return new M({width:b,
height:c,pixels:[h,f,p],pixelType:"U8",mask:r,statistics:[{minValue:k,maxValue:v},{minValue:n,maxValue:w},{minValue:t,maxValue:u}]})},_useBrowserDecoding:function(){return(void 0===this.pixelFilter||null===this.pixelFilter)&&("jpeg"===this.format.toLowerCase()||"jpg"===this.format.toLowerCase()||-1<this.format.toLowerCase().indexOf("png"))},getMultidimensionalInfo:function(){var a=this._url.path+"/multiDimensionalInfo",b=new l(m._dfdCanceller);if(this._multidimensionalInfo)return b.resolve(this._multidimensionalInfo),
b;!this.loaded||10.3<=this.version&&this.hasMultidimensions?(b._pendingDfd=x({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(f.hitch(this,function(a){this._multidimensionalInfo=a.multidimensionalInfo;b.callback(a.multidimensionalInfo)}),function(a){b.errback(a)})):(a=Error("Layer does not support multidimensional info"),a.log=!!D.isDebug,b.errback(a));return b},getVariableStats:function(a){var b=new l,c=f.clone(this.url);if(this._cachedVariableStats[a])b.resolve(this._cachedVariableStats[a]);
else{var d=this.url.indexOf("?token");-1<d&&(c=c.substring(0,d));x({url:c+"/statistics",content:{f:"json",variable:a},handleAs:"json",callbackParamName:"callback",load:f.hitch(this,function(c){this._cachedVariableStats[a]=c.statistics;b.resolve(c.statistics)}),error:function(a){b.reject(a)}})}return b},getDefaultMultidimensionalDefinition:function(){var a=new l(m._dfdCanceller);if(this._defaultMultidimensionalDefinition)return a.resolve(f.clone(this._defaultMultidimensionalDefinition)),a;a._pendingDfd=
this.getMultidimensionalInfo();a._pendingDfd.then(f.hitch(this,function(b){b=this._getDefaultMultidimensionalDefinition(b);a.callback(b)}),function(b){a.errback(b)});return a},_getDefaultMultidimensionalDefinition:function(a,b,c){var d,e=[],g="",h=a.variables[0].dimensions;c&&(g=a.variables[0].name);for(d in h)h.hasOwnProperty(d)&&(b||"StdTime"!==h[d].name)&&(a=h[d],e.push(new O({variableName:g,dimensionName:a.name,isSlice:!a.hasRanges,values:[this._getDefaultDimensionValue(a)]})));this._defaultMultidimensionalDefinition=
e;return f.clone(e)},_getDefaultDimensionValue:function(a){if(a&&a.values&&a.values.length){var b,c,d=Infinity,e,g;if(a.hasRanges)return a.values[0];if(a.name&&"stdz"===a.name.toLowerCase()){for(g=0;g<a.values.length&&(e=a.values[g],c=Math.abs(e-0),c<d&&(d=c,b=e),0!==c);g++);return b}return a.extent[0]}},_setDefaultMultidimensionalDefinition:function(a){var b,c={};this.getDefaultMultidimensionalDefinition().then(f.hitch(this,function(d){b=d;0<b.length&&(this.mosaicRule?(c=f.clone(this.mosaicRule),
c.multidimensionalDefinition=b):this.defaultMosaicRule?(c=f.clone(this.defaultMosaicRule),c.multidimensionalDefinition=b):c=new C({multidimensionalDefinition:b}),this.setMosaicRule(c,a))}))},_setDefaultRenderingRule:function(a){var b={},c=this.renderingRule;if(!c&&"esri.layers.ArcGISImageServiceVectorLayer"!==this.declaredClass&&!this.bandIds&&this.rasterFunctionInfos&&this.rasterFunctionInfos.length&&"none"!==this.rasterFunctionInfos[0].name.toLowerCase())b.rasterFunction=this.rasterFunctionInfos[0].name;
else if("esri.layers.ArcGISImageServiceVectorLayer"===this.declaredClass&&10.3<this.version&&(!c||"Resample"!==c.functionName)){var d="esriImageServiceDataTypeVector-UV"===this.serviceDataType?7:10;b.rasterFunction="Resample";b.rasterFunctionArguments={ResamplingType:d,InputCellSize:{x:this.pixelSizeX,y:this.pixelSizeY}};c&&(b.rasterFunctionArguments.Raster=c.toJson())}b.hasOwnProperty("rasterFunction")&&(this.defaultRenderingRule=new y(b),this.setRenderingRule(this.defaultRenderingRule,a))},_cleanupRequestParams:function(a){if(!a)return a;
if(a.time&&a.mosaicRule){var b=new C(q.fromJson(a.mosaicRule)),b=this._filterOutTimeDimension(b);a.mosaicRule=q.toJson(b.toJson())}var b="displayOnPan drawMode styling id opacity visible resourceInfo useMapDimensionValue extent renderer".split(" "),c;for(c in b)a.hasOwnProperty(b[c])&&delete a[b[c]];return a},_filterOutTimeDimension:function(a){if(this._isMultidimensionalCRF())return a;if(a&&a.multidimensionalDefinition&&0<a.multidimensionalDefinition.length){var b=n.filter(a.multidimensionalDefinition,
function(a){return"StdTime"!==a.dimensionName});a.multidimensionalDefinition=b}return a},_removeVisualizationStretchFunction:function(a){var b=a&&a.functionName;if(!b||"stretch"!==b.toLowerCase())return a;var c=a.functionArguments.Raster;return c&&c.functionName&&n.some(this.rasterFunctionInfos,function(a){return c.functionName===a.name})?c:a},_isMultidimensionalCRF:function(){return 10.71<=this.version&&this.hasMultidimensions&&this.timeInfo&&!(this.objectIdField&&this.fields&&1<this.fields.length)},
_isTimeSupportedOnCRF:function(){return 10.8<=this.version},_cleanupMultidimensionalDefinition:function(a){a&&a.multidimensionalDefinition&&(a.multidimensionalDefinition=a.multidimensionalDefinition.filter(function(a){return!(!a.variableName&&!a.dimensionName)}),0===a.multidimensionalDefinition.length&&(a.multidimensionalDefinition=null))},_isScientificData:function(){return"esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType||
"esriImageServiceDataTypeScientific"===this.serviceDataType},_isVectorData:function(a){a=(a=a||this)&&a.serviceDataType;return"esriImageServiceDataTypeVector-UV"===a||"esriImageServiceDataTypeVector-MagDir"===a},_isRenderingRuleAProcessingTemplate:function(a){var b=a&&a.functionName;return!b||a.functionArguments?!1:n.some(b&&(this.rasterFunctionInfos||[]),function(a){return a&&a.name&&a.name.toLowerCase()===b.toLowerCase()})},_getRenderingRuleId:function(a){var b=a&&a.functionName;if(b){if(this._isRenderingRuleAProcessingTemplate(a))return b;
var c=this._customRenderingRuleId[b];if(c){if(c!==a){for(var d in this._customRenderingRuleId)if(this._customRenderingRuleId[d]===a)return d;for(c=0;this._customRenderingRuleId[e];)c+=1;var e;this._customRenderingRuleId[b+c]=a}}else this._customRenderingRuleId[b]=a;return b}},_createPixelData:function(a){a=new M({width:2,height:2,pixels:a,pixelType:this.pixelType,statistics:a});var b=this.fullExtent.getCenter(),b=new K(b.x,b.y,b.x+this.pixelSizeX,b.y+this.pixelSizeY,this.spatialReference);return{pixelBlock:a,
extent:b}},_convertRendererToRenderingRule:function(a){var b=a&&a.declaredClass;if(!b||"esri.renderer.UniqueValueRenderer"!==b&&"esri.renderer.ClassBreaksRenderer"!==b&&"esri.renderer.StretchRenderer"!==b&&"esri.renderer.ShadedReliefRenderer"!==b&&"esri.renderer.ColormapRenderer"!==b)return null;var c=null;"esri.renderer.StretchRenderer"===b?c=a.toRenderingRule({convertToColormap:10.6>this.version}):"esri.renderer.ClassBreaksRenderer"===b?c=this._convertClassifyRenderer(a):"esri.renderer.UniqueValueRenderer"===
b?c=this._convertUniqueValueRenderer(a):"esri.renderer.ShadedReliefRenderer"===b?c=this._convertShadedReliefRenderer(a):"esri.renderer.ColormapRenderer"===b&&(c=this._convertColormapRenderer(a));return c},_getValueField:function(a){if(a&&a.length){var b,c;n.some(a,function(a){if((c=a.name)&&"value"===c.toLowerCase())return b=c,!0});return b}},_convertColormapRenderer:function(a){var b=new y;b.functionName="Colormap";b.functionArguments={};a=a.colormapInfos.map(function(a){return[a.value].concat(a.color)});
b.functionArguments.Colormap=a;return b},_convertShadedReliefRenderer:function(a){var b=new y;b.functionName="Hillshade";var c="traditional"===a.hillshadeType?0:1,d="none"===a.scalingType?1:3,e={HillshadeType:c,SlopeType:d,ZFactor:a.zFactor};0===c&&(e.Azimuth=a.azimuth,e.Altitude=a.altitude);3===d&&(e.PSPower=a.pixelSizePower,e.PSZFactor=a.pixelSizeFactor);b.functionArguments=e;b.variableName="Raster";a.colorRamp&&(b.functionName="ShadedRelief",e.Colormap=W.convertColorRampToColormap(a.colorRamp,
256));return b},_convertClassifyRenderer:function(a){var b,c=[],d=[],e=[],g=[],h;b=this.renderingRule&&this._getRenderingRuleId(this.renderingRule);var f,p,l=this.hasRasterAttributeTable,k,m;b&&(l=this._rasterFunctionTemplateInfos[b]?this._rasterFunctionTemplateInfos[b].hasRasterAttributeTable:this.hasRasterAttributeTable,p=this._renderingRuleAttributeTable[b],m=this._rasterFunctionTemplateInfos[b]);f=p&&p.features?p.features:this._rasterAttributeTableFeatures;k=this._getValueField(p&&p.fields?p.fields:
this._rasterAttributeTableFields);l&&f?(n.forEach(a.infos,function(b,c){var d,e=b.symbol.color;e.a&&n.forEach(f,function(f){d=f.attributes[a.attributeField];(d>=b.minValue&&d<b.maxValue||c===a.infos.length-1&&d>=b.minValue)&&g.push([f.attributes[k],e.r,e.g,e.b])},this)},this),b=m&&m.pixelType||this.pixelType,this._adjustColormapToPixelTypeRange(g,b),b=new y,b.functionName="Colormap",b.functionArguments={},b.functionArguments.Colormap=g,b.variableName="Raster"):(n.forEach(a.infos,function(a,b){h=a.symbol&&
a.symbol.color;h.a?(0===b?c.push.call(c,a.minValue,a.maxValue+1E-4):c.push.call(c,a.minValue+1E-4,a.maxValue+1E-4),d.push(b),g.push([b,h.r,h.g,h.b])):e.push(a.minValue,a.maxValue)}),b=m&&m.pixelType||this.pixelType,this._adjustColormapToPixelTypeRange(g,b),b=new y,b.functionName="Remap",b.functionArguments={InputRanges:c,OutputValues:d,NoDataRanges:e},b.variableName="Raster",p=new y,p.functionName="Colormap",p.functionArguments={Colormap:g,Raster:b},b=p);return b},_convertUniqueValueRenderer:function(a){var b=
[],c=this.renderingRule&&this._getRenderingRuleId(this.renderingRule),d,e,g,f;c&&(e=this._renderingRuleAttributeTable[c],f=this._rasterFunctionTemplateInfos[c]);d=e&&e.features?e.features:this._rasterAttributeTableFeatures;g=(c=e&&e.fields?e.fields:this._rasterAttributeTableFields)&&c.length?this._getValueField(c):"Value";n.forEach(a.infos,function(c){var e=c.symbol.color;e.a&&(a.attributeField!==g&&d?n.forEach(d,function(d){d.attributes[a.attributeField]==c.value&&b.push([d.attributes[g],e.r,e.g,
e.b])},this):b.push([c.value,e.r,e.g,e.b]))},this);this._adjustColormapToPixelTypeRange(b,f&&f.pixelType||this.pixelType);f=new y;f.functionName="Colormap";f.functionArguments={};f.functionArguments.Colormap=b;f.variableName="Raster";return f},_adjustColormapToPixelTypeRange:function(a,b){(b=this._pixelTypeRanges[b])&&a.push([Math.floor(b[0]-1),0,0,0],[Math.ceil(b[1]+1),0,0,0]);return a},_combineRenderingRule:function(a,b){if(!a||!b)return a||b;var c=function(a){var b=a.Raster;return b=b&&"esri.layers.RasterFunction"===
b.declaredClass?c(b.functionArguments):a};a=f.clone(a);"none"!==b.functionName.toLocaleLowerCase()&&(c(a.functionArguments).Raster=b);return a},_isItemLevelRasterFunction:function(a){var b=a&&a.functionName;if(!b||!this._hasItemLevelRFT)return!1;var c=!1;n.some(this.rasterFunctionInfos,function(a){if(a&&a.name===b){if(1===a.functionType||2===a.functionType)c=!0;return!0}});return c},_getServiceLevelRenderingRule:function(a){if(!this._hasItemLevelRFT||!a)return a;a=new y(a.toJson());var b;b=a.functionArguments;
for(var c;;)if((c=b&&b.Raster)&&c.functionArguments&&c.functionArguments.Raster)b=c,b=b.functionArguments;else{this._isItemLevelRasterFunction(c)&&delete b.Raster;break}return a},_getItemLevelRenderingRule:function(a){if(!this._hasItemLevelRFT||!a)return null;if(this._isItemLevelRasterFunction(a))return a;a=new y(a.toJson());for(a=a.functionArguments;;)if((a=a&&a.Raster)&&a.functionArguments&&a.functionArguments.Raster)a=a.functionArguments;else{if(this._isItemLevelRasterFunction(a))return a;break}},
_resolve:function(a,b,c,d,e){b&&this[b].apply(this,a);c&&c.apply(null,a);d&&m._resDfd(d,a,e)},_toggleTime:function(){var a=this._map;this.timeInfo&&this.useMapTime&&a&&!this.suspended?(this._timeConnect||(this._timeConnect=N.connect(a,"onTimeExtentChange",this,this._onTimeExtentChangeHandler)),this._setTime(a.timeExtent)):(N.disconnect(this._timeConnect),this._timeConnect=null,this._setTime(null))},setUseMapTime:function(a,b){this.useMapTime=a;this._toggleTime();!b&&this._map&&this.refresh(!0)},_setTime:function(a){this._params&&
(this._params.time=a?a.toJson().join(","):null)},_onTimeExtentChangeHandler:function(a){this.suspended||(this._setTime(a),this.refresh(!0))},handleSpatialReferenceChange:function(){this.onSpatialReferenceChange()},getColormap:function(a){var b=this._url.path+"/colormap",c=new l(m._dfdCanceller),d={f:"json"};a&&a.renderingRule&&(d.renderingRule=q.toJson(a.renderingRule.toJson()));this.hasColormap?(c._pendingDfd=x({url:b,content:d,handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(a){c.callback(a)},
function(a){c.errback(a)})):(a=Error("Layer does not support colormap"),a.log=!!D.isDebug,c.errback(a));return c},getRenderingRuleColormap:function(a){var b=new l(m._dfdCanceller);if(!a||!a.renderingRule)return b.errback(Error("Rendering rule is not specified")),b;a=a.renderingRule;var c=this._getRenderingRuleId(a);this._renderingRuleColormap&&c&&this._renderingRuleColormap.hasOwnProperty(c)?b.resolve(this._renderingRuleColormap[c]):b=this.getColormap({renderingRule:a}).then(f.hitch(this,function(a){a=
a&&a.colormap;c&&(this._renderingRuleColormap[c]=a);return a}));return b}});Q("extend-esri")&&f.setObject("layers.ImageServiceLayerMixin",J,S);return J});