// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.34/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/tasks/parsers/DataXMLParser","esri/units esri/dijit/geoenrichment/utils/FieldUtil esri/dijit/geoenrichment/utils/JsonXmlConverter ../../data/AreaDataUtil ../../../../core/supportClasses/DocumentOptions ./AttrUtil esri/dijit/geoenrichment/ReportPlayer/config esri/dijit/geoenrichment/ReportPlayer/_devConfig".split(" "),function(k,q,h,r,t,u,v,n){function l(e){return e.innerHTML?e.innerHTML:e.tags&&e.tags.length&&e.tags[0].text||
""}function w(e){var g={Title:null,Subtitle:null,country:null,hierarchyId:null,exportSettings:null};e.tags&&e.tags.forEach(function(a){"ReportTitle"===a.name&&(g.Title=l(a));"ReportTitle2"===a.name&&(g.Subtitle=l(a));if("CurrencyFormat"===a.name){a=l(a);var e=a.split(";")[0].replace("0","").trim();g.country={id:null,currencySymbol:e,currencyFormat:a}}else if("ReportLayout"===a.name){var d=g.exportSettings={};a.tags&&a.tags.forEach(function(c){if("Options"===c.name&&c.attributes)d.addHeader=!!c.attributes.header,
d.addDataSource=!!c.attributes.dataSource,d.addFooter=!!c.attributes.footer;else if("Page"===c.name&&c.attributes){d.pageSettings={};var b=c.attributes;if(b.width&&b.height&&b.units){c=Number(b.width);var a=Number(b.height);if(b=b.units===k.MILLIMETERS?"mm":b.units===k.CENTIMETERS?"cm":b.units===k.INCHES?"in":b.units===k.POINTS?"pt":null)d.pageSettings.pagesize=t.combineCustomSizeString(c,a,b)}else b.size&&b.orientation&&(d.pageSettings.pagesize=b.size.toLowerCase(),d.pageSettings.orientation=b.orientation.toLowerCase())}})}});
g.exportSettings&&g.Subtitle&&(g.exportSettings.reportSubtitle=g.Subtitle);return g}function x(e){function g(c){c.tags&&c.tags.forEach(function(b,c){c=b.attributes&&b.attributes.STORE_ID||c+"";var a=d[c];a||(a={attributes:null,notes:null,images:null},d[c]=a,f.sites.push(a));b.tags&&b.tags.forEach(function(b){"Attributes"===b.name&&b.tags&&(a.attributes=b.tags.map(function(b){return{name:b.attributes.Name,alias:b.attributes.Alias,type:b.attributes.Type,value:q.isNumericField(b.attributes.Type)?Number(b.attributes.Value):
b.attributes.Value}}));"Notes"===b.name&&b.tags&&(a.notes=b.tags&&b.tags.map(function(b){return{text:b.attributes.Text}}));"Images"===b.name&&b.tags&&(a.images=b.tags&&b.tags.map(function(b){return{url:b.attributes.Source,thumbnail:b.attributes.Thumbnail,description:b.attributes.Description,imageViewType:null}}))})})}function a(a){var b;f.stdLevels=a.tags&&a.tags.map(function(a,c){b=b||a.attributes.Id.substr(0,a.attributes.Id.indexOf("."));return{id:a.attributes.Id,name:a.attributes.Caption,isWholeCountry:a.attributes.IsWholeCountry||
0===c}});"US"===b&&(f.countrId="US");"CAN"===b&&(f.countrId="CA")}var f={sites:[],stdLevels:null,countrId:null},d={};e.tags&&e.tags.forEach(function(c){"StudyAreas"===c.name?g(c):"StandardGeographyLevels"===c.name&&a(c)});return f}function y(e,g){function a(a){if(a=function(a){var e={},f,k,m;a.tags.forEach(function(c){var d=l(c),h=d,p=b[a.name][c.name];"string"===(p&&p.type)?d=String(d):(d=Number(d),isNaN(d)&&(d=h),n.emulateErrors.createReportNaN&&(d=NaN),n.emulateErrors.createReportNull&&(d=null));
g&&(d=g(c.name,d,a.name));void 0===e[c.name]&&(e[c.name]=d);"AREA_ID"===c.name&&(f=d);"IDFNDFIELD"===c.name&&(k=d);"STORE_ID"===c.name&&(m=d)});f=f||k;if(!f&&!m)return null;var h;!f&&m&&(h=Number(m));f&&void 0===d[f]&&(d[f]=c++);u.cleanUpAttrs(e,v.isPlayerOnServer?{STORE_ID:1,AREA_ID:1}:null);return{name:a.name,attrs:e,areaIndex:void 0!==h?h:d[f]}}(a)){var e=f[a.areaIndex]=f[a.areaIndex]||{};e[a.name]?e[a.name].comparisonLevels.push(a.attrs):e[a.name]=r.createCalculator(a.attrs)}}var f=[],d={},c=
0,b;e.tags[0].tags.forEach(function(c){"xs:schema"===c.name?b=z.parseSchema(c):a(c)});return{areaData:f,schemaParseResult:b}}var z={parseSchema:function(e){var g={};e.tags.forEach(function(a){"xs:element"===a.name&&a.attributes&&"ReportData"===a.attributes.name&&h.queryJson(a,"xs:element").filter(function(a){return!!a.tags}).forEach(function(a){var d=g[a.attributes.name]={};h.queryJson(a,"xs:element").forEach(function(a){d[a.attributes.name]={type:"xs:string"===a.attributes.type?"string":"number",
alias:a.attributes["msdata:Caption"]||"",vintage:a.attributes["msdata:Vintage"]||"",source:a.attributes["msdata:Source"]||""}})})});return g}};return{parse:function(e,g){return this._parseDataXmlJson(h.parseXml(e,{saveInnerHTML:!0}),g)},_parseDataXmlJson:function(e,g){if(!e||!e.tags||2>e.tags.length)return[];var a,f,d,c;e.tags.forEach(function(b){"ReportInfo"===b.name?a=w(b):"ReportArea"===b.name?f=x(b):"ReportData"===b.name&&(b=y(b,g),c=b.areaData,d=b.schemaParseResult)});n.logData&&(console.log("DataXMLPareser.js \x3d\x3e areaData:"),
console.log(c));f&&(a.country.id=f.countrId,a.sites=f.sites,a.stdLevels=f.stdLevels);a.variables=d;return{reportInfo:a,areaData:c}}}});